pytorch/text

- torchtext/data.py
Add fields column in the return values of fromCSV, as referred in issue #16
> Fix for issue #16

- requirements.txt
- torchtext/__init__.py
- torchtext/utils.py
- torchtext/vocab.py
Downloading and parsing the text vectors can take up to 15 minutes all told. This adds a progress bar to indicate the current state.
> Add progress indicator to vector download and vector preprocessing

- torchtext/data.py
This PR fixes the bug referred by https://github.com/pytorch/text/pull/29#issuecomment-296878933.
> Fix Python 3 compatibility

- torchtext/vocab.py
in python 2.7, there is exception for decoding word into utf8.
So I added the type checking and converting UTF8 codes.
> fix non-UTF8 error

- setup.py
- torchtext/data.py
- torchtext/vocab.py
Noticed a few unused imports, etc while reading through the package code.
Also some cosmetic fixes.
> Minor cleanup

- .flake8
- .travis.yml
- build_tools/travis/after_success.sh
- build_tools/travis/install.sh
- build_tools/travis/test_script.sh
- codecov.yml
- pytest.ini
- requirements.txt
- test/test_data.py
- torchtext/data.py
- torchtext/datasets/__init__.py
- torchtext/datasets/language_modeling.py
- torchtext/datasets/sentiment.py
- torchtext/vocab.py
This PR sets up the beginnings of a test suite, runs it on CI with TravisCI, and logs coverage statistics with codecov.
To Do:
This isn't ready for review yet, but I thought it'd put it here in case you had feedback / wanted to push to it as well; I'll let you know when it is ready to be seriously looked at. 
You (or maybe @soumith / @apaszke , not sure what permissions you have on the repo) might have to twiddle some bits to get Travis and Codecov running on this repo. It should be fairly self explanatory, you just log into to the respective sites with your Github username and add the pytorch/text project to be tested / covered, and it should automatically start doing so. I've set them up on my fork already ([travis](https://travis-ci.org/nelson-liu/text/), …
> [MRG] Set up tests, CI, and coverage

- README.md
Just a quick PR to add the badges to the README.
> Add build status and coverage badges to README

- torchtext/data/field.py
> update preprocess to always convert to unicode

- torchtext/data/field.py
Achieves a 87% speedup in dataset loading time when using the default `Field.preprocessing` and `Field.postprocessing` values.
> Don't run Pipeline.__call__ for default pre/postprocessing

- test/data/test_field.py
- torchtext/data/field.py
> Prevent decoding unicode strs to unicode in Py2

- torchtext/vocab.py
> fix max_size

- torchtext/data/iterator.py
> sort should override shuffle

- torchtext/data/iterator.py
Blegh, had this fixed locally for a while but hadn't pushed. This is an awful bug that was kind of hard to track down, so I hope I haven't wasted anyone else's time.
> Fix dynamic batching bug

- torchtext/vocab.py
> Fix min_freq validation

- torchtext/data/iterator.py
> Fix Py2 Iterator length bug

- test/common/torchtext_test_case.py
- test/data/test_dataset.py
- test/data/test_field.py
- test/data/test_utils.py
- torchtext/data/dataset.py
- torchtext/data/example.py
> Dataset fixes and tests for non-squash merge

- torchtext/data/dataset.py
- torchtext/datasets/translation.py
Allows users to download multiple language pairs with the same class
> iwslt multiple language pairs

- README.md
> Update README.md to fix #133

- torchtext/data/dataset.py
Adds types to function arguments and generally cleans up the docstrings.
> Update and clean up Dataset docstrings

- torchtext/data/iterator.py
> Improve sort logic

- torchtext/datasets/translation.py
> Fix Multi30k test set URL

- test/test_vocab.py
- torchtext/vocab.py
> Fix word vector strings on Py2

- torchtext/data/field.py
> out-of-place transpose in reverse

- torchtext/datasets/translation.py
This causes problems when subclassing it.
> TranslationDataset.splits is redundant and unhelpful

- torchtext/data/field.py
Option for padding the sentence at the beginning or the end (True/False).
> Adding "pad_first" option in Field

- torchtext/datasets/translation.py
Reverts pytorch/text#156, which was just...wrong and broke things
> Revert "TranslationDataset.splits is redundant and unhelpful"

- torchtext/datasets/translation.py
The test set tarball moved, and we dealt with that, but the name of the file inside moved too and we didn't
> Fix Flickr30k filename

- torchtext/vocab.py
> Fix vocab constructor side effect

- torchtext/vocab.py
> Simplify the process of Vocab initialization

- torchtext/datasets/translation.py
> fix TranslationDataset.splits for custom datasets

- torchtext/data/dataset.py
Removed duplicated description of 'fields' argument.
> Fix a typo in dataset.py

- test/common/torchtext_test_case.py
- test/data/test_batch.py
- test/data/test_dataset.py
- torchtext/data/batch.py
- torchtext/data/dataset.py
- Fixed bug with batch containing missing fields
- Also fixed bug when using data.Iterator with TabularDataset created using csv file and a dict for the fields that was introduced due to a minor error I made in the implementation
> Fixed bug with batch containing missing fields (#219)

- test/common/torchtext_test_case.py
- test/data/test_batch.py
- test/data/test_builtin_datasets.py
- test/data/test_dataset.py
- torchtext/data/batch.py
- torchtext/data/dataset.py
- torchtext/datasets/__init__.py
- torchtext/datasets/language_modeling.py
- Dealt with #228 (Encoding issue for LanguageModelingDataset)
- Added Penn Treebank dataset (commonly used dataset, so should be worth having)
- Added tests for built-in datasets
> Fixes and features around language modeling

- torchtext/data/batch.py
Fixed a couple of bugs with torch `master`
- 'from torch.tensor import _TensorBase' outright crashed since there is no longer a torch.tensor module
- made the str a bit more robust (now it handles include_lengths properly)
Tested on 0.3 & master.
> fix compatibility of batch __str__ with torch v3 and v4

- torchtext/data/batch.py
> use getattr in Batch constructor

- torchtext/vocab.py
This enables setting vectors cache location and init strategy for unk words.
Also fixing broken calls to load_vectors.
> Enable passing args to Vectors constructor.

- torchtext/data/iterator.py
such that it does not shuffle/sort when iterator does not (#242)
> fix pool method

- test/test_vocab.py
Add a test to check that we can cache vectors into a custom location.
> Test custom vector cache

- torchtext/data/dataset.py
Fixes  #278, while kind of ugly.
> Copy the sort key while splitting datasets

- torchtext/vocab.py
Fixes #300; could perhaps do with further testing
> Create non-existent cache dirs for pretrained embeddings

- README.rst
- test/nli.py
- torchtext/datasets/__init__.py
- torchtext/datasets/nli.py
Added MultiNLI dataset: http://www.nyu.edu/projects/bowman/multinli/
> added MultiNLI

- torchtext/datasets/translation.py
Fixes #289 by using codecs instead of io
> Fix clean method in iwslt

- docs/source/datasets.rst
- torchtext/data/dataset.py
- torchtext/data/field.py
- torchtext/datasets/__init__.py
- torchtext/vocab.py
- Add missing data sets class to document file
- Fix indents
- Add missing arguments
> Fix document

- docs/requirements.txt
- docs/source/conf.py
- setup.py
- Just put the torch dependency in `setup.py` instead of requirements
> Rtd final fix

- torchtext/datasets/translation.py
> Swap open with io open in translation dataset

- .flake8
- test/common/torchtext_test_case.py
- torchtext/data/batch.py
- torchtext/data/field.py
- torchtext/data/iterator.py
- torchtext/datasets/babi.py
- torchtext/vocab.py
Fix updated code style errors (W504, W605)
> Fix code style according to flake8 update

- docs/source/data.rst
added 'for' word in 'The data module provides the following' section
> better description

- test/sst.py
* fix dead url for fasttext wiki.simple.vec
> fix dead url for wiki.simple.vec in tests

- torchtext/vocab.py
processing bar mistake when using max_vectors
> bug fix: processing bar mistake

- test/common/test_markers.py
- torchtext/vocab.py
It fails in the travis CI test.
> Fix CharNGram

- docs/requirements.txt
- docs/source/conf.py
> Updating theme.

- build_tools/conda/torchtext/meta.yaml
meta.yaml that I used for taking v0.4.0 live
> conda build for torchtext

- README.rst
Add a claimer for torchtext datasets.
> Torchtext dataset claimer

- torchtext/data/dataset.py
> fix Dataset docstring

- build_tools/travis/install.sh
- torchtext/__init__.py
Update the version number
Link the CI tests to pytorch 1.4.0-RC
> Version number and CI

- .travis.yml
- build_tools/travis/install.sh
- torchtext/__init__.py
Bump the version number to 0.5.1
Remove CI test for Python2.7
CI test depending on pytorch nightly release
> Master branch to 0.5.1

- torchtext/experimental/datasets/language_modeling.py
Update doc of WikiText2/WikiText103/PennTreebank
> update doc in torchtext.experimental.datasets.language_modeling

- test/data/test_builtin_datasets.py
- torchtext/experimental/datasets/text_classification.py
Bug fix. Allow to build experimental IMDB dataset with a custom vocab. Fix https://github.com/pytorch/text/issues/681
> Bug fix in experimental IMDB

- README.rst
- torchtext/data/metrics.py
Fix https://github.com/pytorch/text/issues/727
> update the example in bleu doc

- build_tools/travis/install.sh
- torchtext/__init__.py
include pytorch 1.5.0-rc3 for CI test
> torchtext 0.6.0 release

- test/data/test_builtin_datasets.py
Update the CI tests of text classification datasets. Include the test results of text tensors.
> Add explicit test results to text classification datasets

- .travis.yml
Then, all the travis tests are not allow to fail in order to be merged.
> Remove the allow to fail statement in travis test

- .travis.yml
@cpuhrsch followup `a)` of #744
> Disable Travis tests of which equivalent run on CCI

- README.rst
Preview -> https://github.com/mthrok/text/tree/badge
> Update build badge

- .circleci/config.yml
- .circleci/config.yml.in
- .circleci/regenerate.py
- packaging/build_conda.sh
- packaging/build_wheel.bat
- packaging/build_wheel.sh
- packaging/pkg_helpers.bash
- packaging/torchtext/bld.bat
- packaging/vs2019/activate.bat
- packaging/vs2019/conda_build_config.yaml
- packaging/vs2019/install_activate.bat
- packaging/vs2019/install_runtime.bat
- packaging/vs2019/meta.yaml
Fixes https://github.com/pytorch/text/issues/703.
> Add binary jobs for Windows

- .circleci/config.yml
- .circleci/config.yml.in
- .circleci/unittest/windows/scripts/install.bat
- packaging/build_wheel.bat
@zhangguanheng66 @mthrok @cpuhrsch
> Fix VC environment activation scripts for Windows jobs

- .circleci/config.yml
- .circleci/config.yml.in
The old image is not available anymore.
> Use new circleci image for Windows jobs

- torchtext/utils.py
Address https://github.com/pytorch/text/issues/760
> Create root directory automatically for download_from_url if not exists

- .circleci/unittest/windows/scripts/install.sh
> Minor fix for batch script cleanup

- .circleci/unittest/windows/scripts/install.sh
> One more fix for Windows jobs

- .circleci/config.yml
- .circleci/config.yml.in
- .circleci/regenerate.py
tested at https://github.com/pytorch/text/pull/830
> Add windows smoke test job to CI

- packaging/build_conda.sh
- packaging/build_wheel.sh
- setup.py
> bump nightlies to 0.8.0

- benchmark/experimental_vectors.py
- test/experimental/test_vectors.py
- torchtext/csrc/vectors.cpp
- torchtext/experimental/vectors.py
- Updating Vectors class to use 2d tensor along with a `unordered map<string, Tensor.view()>`
- After conducting performance benchmarks, it was found that this implementation gives the best mix of performance for lookup and construction
- Added functionality for looking up vectors for several tokens using `get_vectors_by_tokens`
- Added tests for the new function
**Construction time from file:** 778.5076372753829
**Construction time from cache:** 6.0479023195803165
**Lookup time:** 132.09116122685373
**Construction time:** 670.8132877256721
**Construction time from cache:** 39.3408519141376
**Lookup time:** 113.68280134536326
**Lookup time:** 224.18116508424282
> Optimizing cpp Vectors class to use 2d tensor

- torchtext/experimental/vocab.py
Add an example to build vocab from a list of tokens.
> Minor update on vocab doc

- benchmark/experimental_vectors.py
- test/experimental/test_vectors.py
- torchtext/csrc/vectors.cpp
- torchtext/experimental/vectors.py
- Added new function to lookup a 2d tensor of vectors given a list of tokens as input
- Added unit tests for the new function
> Added `lookup_tokens()` function to Vectors class

- test/experimental/test_vectors.py
- Disabling all glove tests due to URL breakage
- Refer to https://github.com/stanfordnlp/GloVe/issues/174
> Disabling glove tests due to URL breakage

- test/experimental/test_vectors.py
- Reenabling GloVe tests after Stanford's cluster maintenance was completed
- Refer to https://github.com/stanfordnlp/GloVe/issues/174
> Reenabling GloVe tests

- torchtext/experimental/vectors.py
- Fixing CI errors for printing Vectors `dtype`
> Fixing error with printing Vectors dtype

- test/data/test_functional.py
- Reenabling more complex test cases for experimental tokenizers following https://github.com/pytorch/pytorch/issues/38207 being closed
> Reenabling experimental tokenizers tests

- torchtext/csrc/common.h
- torchtext/csrc/regex_tokenizer.cpp
- torchtext/csrc/register_bindings.cpp
- torchtext/csrc/sentencepiece.cpp
- torchtext/csrc/sentencepiece.h
- torchtext/csrc/vectors.cpp
- torchtext/csrc/vectors.h
- torchtext/csrc/vocab.cpp
- torchtext/csrc/vocab.h
- Creating header files for all C++ classes
- Moving all torchtext binding registrations to a separate file
> Create header files for all C++ classes

- test/experimental/test_vocab.py
- torchtext/csrc/vocab.cpp
- torchtext/experimental/vocab.py
- Moved `unk_token` to beginning of Vocab class by default
- Updated unit tests
> Moved unk_token to beginning of Vocab by default

- test/experimental/test_vectors.py
- test/experimental/test_vocab.py
- torchtext/experimental/vectors.py
- torchtext/experimental/vocab.py
- Added `__call__` method to Vocab and Vectors
- Added unit tests
> Added __call__ method to Vocab and Vectors

- test/experimental/test_vocab.py
> fix __call__ func test in test_vocab

- docs/source/experimental_vectors.rst
- Added `vector` factory method to docs
> Updated Vector docs to include factory method

- torchtext/experimental/vocab.py
- Updating example doc strings for Vocab factory methods
> Updated Vocab factory examples

- .circleci/unittest/linux/scripts/environment.yml
- .circleci/unittest/windows/scripts/environment.yml
> .circleci: Add dataclasses to dependencies for environment.yml

- test/experimental/test_vocab.py
- torchtext/csrc/vocab.cpp
- Updated `parse_raw_text_file_chunk` to pass in a list of tokens to JIT tokenizer
> Updated vocab function to pass list of tokens to JIT tokenizer

- examples/data_pipeline/pipelines.py
- examples/data_pipeline/transforms.py
- torchtext/experimental/functional.py
> fix master branch

- examples/data_pipeline/pipelines.py
- test/experimental/test_vocab.py
- torchtext/experimental/vectors.py
Import a few changes for lint errors fixed within fbcode.
> Sync with fbcode

- examples/BERT/qa_task.py
- test/data/test_builtin_datasets.py
- torchtext/experimental/datasets/question_answer.py
- torchtext/experimental/datasets/raw/question_answer.py
Switch the output from a dictionary to a tuple of (context, question, answers, ans_pos). This is consistent with other experimental datasets.
> Update experimental SQuAD1 and SQuAD2 datasets

- torchtext/experimental/transforms.py
- torchtext/experimental/vectors.py
- torchtext/experimental/vocab.py
related to PR https://github.com/pytorch/pytorch/pull/42390
> Ignore @property decorator when calling torch.jit.script

- torchtext/experimental/datasets/raw/text_classification.py
- torchtext/experimental/datasets/text_classification.py
Update the experimental raw IMDB dataset to return raw label
> Update the experimental raw IMDB dataset to return raw label

- benchmark/data_construction.py
- torchtext/experimental/datasets/language_modeling.py
- torchtext/experimental/datasets/question_answer.py
- torchtext/experimental/datasets/raw/common.py
- torchtext/experimental/datasets/raw/language_modeling.py
- torchtext/experimental/datasets/raw/question_answer.py
- torchtext/experimental/datasets/raw/sequence_tagging.py
- torchtext/experimental/datasets/raw/text_classification.py
- torchtext/experimental/datasets/raw/translation.py
- torchtext/experimental/datasets/sequence_tagging.py
- torchtext/experimental/datasets/text_classification.py
- torchtext/experimental/datasets/translation.py
- torchtext/vocab.py
All datasets used within the experimental raw datasets are in fact very similar.
> Define RawTextIterableDataset as common dataset for all raw iterators and store NUM_LINES.

- torchtext/experimental/datasets/raw/text_classification.py
Update AG_NEWS with a more stable URL.
> Update AG_NEWS url

- torchtext/experimental/datasets/language_modeling.py
- torchtext/experimental/datasets/question_answer.py
- torchtext/experimental/datasets/raw/language_modeling.py
- torchtext/experimental/datasets/raw/question_answer.py
- torchtext/experimental/datasets/raw/sequence_tagging.py
- torchtext/experimental/datasets/raw/text_classification.py
- torchtext/experimental/datasets/raw/translation.py
- torchtext/experimental/datasets/sequence_tagging.py
- torchtext/experimental/datasets/text_classification.py
- torchtext/experimental/datasets/translation.py
Add explicit arguments to the dataset constructors for better docs.
> Add explicit argus to the dataset constructors in the experimental folder

- .circleci/config.yml
- .circleci/config.yml.in
> .circleci: Install binaries directly from cpu

- torchtext/experimental/datasets/language_modeling.py
- torchtext/experimental/datasets/question_answer.py
- torchtext/experimental/datasets/text_classification.py
- torchtext/experimental/datasets/translation.py
Datasets should only allocate subset of raw dataset iterators based on data_select:
- Language modeling
- Question answer
- text classification
- Translation
Sequence tagging datasets have been already updated so no changes are required there.
> Check out the datasets in data_select only

- test/data/test_builtin_datasets.py
This PR includes:
- Add more tests to cover the scenario for the subset of datasets
> Add more tests to cover the subset of datasets

- benchmark/data_construction.py
- torchtext/experimental/datasets/raw/common.py
- torchtext/experimental/datasets/raw/question_answer.py
- torchtext/experimental/datasets/raw/sequence_tagging.py
- torchtext/experimental/datasets/raw/text_classification.py
Import a few lint error fix from fbcode.
> Sync with fbcode on October 12

- torchtext/experimental/datasets/raw/translation.py
- torchtext/experimental/datasets/translation.py
Fix https://github.com/pytorch/text/issues/1038
> Update the example docs in the experimental translation datasets

- docs/source/index.rst
Updated index page to include links to PyTorch libraries and describe feature classification.
> Update to index.rst

- README.rst
Adding in README the necessary environment variables for building the project from source on MacOS.
> Adding OSX environment variables on readme.

- README.rst
I found a few mistakes in the README, so I fixed them!
> Fix grammar mistakes in README

- test/data/test_batch.py
> fixing_two_warnings in test_batch.py

- .circleci/build_docs/commit_docs.sh
Continuation of gh-1105, gh-1111
Copy-paste failure: I did not update the target to this repo. It is a good thing the push failed.
> DOC: fix typo

- .flake8
- test/data/test_builtin_datasets.py
- torchtext/experimental/datasets/raw/language_modeling.py
- torchtext/nn/modules/multiheadattention.py
Fix the lint errors when landing diff in fbcode. Those fixes are exported into the fbsync branch.
> Merge fbsync into master branch on 1/11/2021

- versions.html
Add a versions.html page to allow selecting between documentation versions
> Add a versions.html

- torchtext/data/datasets_utils.py
> Fix the number of lines docs in datasets

- docs/source/datasets.rst
Updating datasets documentation to include label and line.
> Fix datasets example documentation

- test/data/test_builtin_datasets.py
Added unit test to verify that str representation of raw dataset iterator matches the dataset name
> Added unit test to verify raw datasets name property

- examples/legacy_tutorial/migration_tutorial.ipynb
Update to use the latest released package.
> Switch to torch 1.8.0 and torchtext 0.9.0 package after the release

- .circleci/config.yml
- .circleci/config.yml.in
Update config to avoid changing cache key between jobs
> workspace to share cache key within jobs

- torchtext/data/datasets_utils.py
- torchtext/datasets/ag_news.py
- torchtext/datasets/amazonreviewfull.py
- torchtext/datasets/amazonreviewpolarity.py
- torchtext/datasets/conll2000chunking.py
- torchtext/datasets/dbpedia.py
- torchtext/datasets/enwik9.py
- torchtext/datasets/imdb.py
- torchtext/datasets/iwslt2016.py
- torchtext/datasets/iwslt2017.py
- torchtext/datasets/penntreebank.py
- torchtext/datasets/sogounews.py
- torchtext/datasets/squad1.py
- torchtext/datasets/squad2.py
- torchtext/datasets/udpos.py
- torchtext/datasets/wikitext103.py
- torchtext/datasets/wikitext2.py
- torchtext/datasets/yahooanswers.py
- torchtext/datasets/yelpreviewfull.py
- torchtext/datasets/yelpreviewpolarity.py
- torchtext/experimental/datasets/raw/multi30k.py
- torchtext/experimental/datasets/raw/wmt14.py
- torchtext/experimental/datasets/raw/wmtnewscrawl.py
Summary:
- collect common file reading functionalities into datasets_utils
- create decorator to add dataset_name sub-folder to the given root folder to avoid cluttering
> Raw datasets cleanup

- benchmark/benchmark_basic_english_normalize.py
- benchmark/benchmark_experimental_vectors.py
- benchmark/benchmark_experimental_vocab.py
- benchmark/benchmark_sentencepiece.py
We have modified our datasets and the way we pass splits and the way datasets are wrapped in decorator. In light of this some of the stuffs in benchmark suit need to be adapted.
> fixing benchmark tests

- versions.html
Continuation of d9a5430f to modify the "old" 0.8.1
> in versions.html change v0.8.1 (stable release) -> 0.8.1

- torchtext/datasets/ag_news.py
- torchtext/datasets/amazonreviewfull.py
- torchtext/datasets/amazonreviewpolarity.py
- torchtext/datasets/conll2000chunking.py
- torchtext/datasets/dbpedia.py
- torchtext/datasets/enwik9.py
- torchtext/datasets/imdb.py
- torchtext/datasets/iwslt2016.py
- torchtext/datasets/iwslt2017.py
- torchtext/datasets/penntreebank.py
- torchtext/datasets/sogounews.py
- torchtext/datasets/squad1.py
- torchtext/datasets/squad2.py
- torchtext/datasets/udpos.py
- torchtext/datasets/wikitext103.py
- torchtext/datasets/wikitext2.py
- torchtext/datasets/yahooanswers.py
- torchtext/datasets/yelpreviewfull.py
- torchtext/datasets/yelpreviewpolarity.py
- torchtext/experimental/datasets/raw/multi30k.py
- torchtext/experimental/datasets/raw/wmt14.py
- torchtext/experimental/datasets/raw/wmtnewscrawl.py
Fixing style checks for dataset files that were introduced in #1233
> fixing stylecheck

- .circleci/config.yml
- .circleci/config.yml.in
> [v0.9.1] .circleci: Bump versions for pytorch 1.8.1

- torchtext/experimental/datasets/translation.py
Fix example code in translation datasets
- IWSLT2016
- IWSLT2017
> Fix examples for translation datasets

- torchtext/data/__init__.py
- torchtext/data/functional.py
adding filter_wikipedia_xml to torchtext.data __init__ module
> adding filter_wikipedia_xml to data __init__ module

- torchtext/csrc/vocab.h
This change is required to compile on fb code
> fixing issue on fb code import

- torchtext/vocab.py
Summary: Adding API usage logging for Vocab module
Reviewed By: colin2328
Differential Revision: D28585537
fbshipit-source-id: 38975b523fb597412fbcb18ef831bfb4834cb420
> [FBcode->GH] Adding API usage logging

- README.rst
Update readme for 0.10 release
> update readme file

- torchtext/models/roberta/model.py
- torchtext/models/roberta/modules.py
Adding option to return all layers or only the last layer in transformer encoder. This would allow downstream models to only request what's necessary out of encoder layer.
> Enable optional return of all states in transformer encoder

- torchtext/models/roberta/modules.py
Rather than raise an exception whenever head_dim != 64, we can just infer the scaling value and continue to provide a warning.
Also add an assertion in case embed_dim is not a multiple of num_heads (in which case forward will break).
> Allow inferred scaling in MultiheadSelfAttention for head_dim != 64

- torchtext/data/metrics.py
`list(ngrams_iterator(token,2)) --> ['me', 'me', 'you', 'me me', 'me you'] `
> Update _compute_ngram_counter docstring in data/metrics.py

- torchtext/experimental/datasets/sst2.py
Summary:
Pull Request resolved: https://github.com/pytorch/data/pull/61
Fixes https://github.com/facebookexternal/torchdata/issues/114 and https://github.com/facebookexternal/torchdata/issues/140
* #59
Test Plan: Imported from OSS
Reviewed By: wenleix
Differential Revision: D31734382
Pulled By: ejguan
fbshipit-source-id: 16d10bace2a473e3878ac8dd5f7b6885bd924105
> [fbsync] Refactor OnDiskCache (#61)

- docs/source/transforms.rst
- test/test_transforms.py
- torchtext/transforms.py
> Add Truncate Transform

- build_tools/setup_helpers/extension.py
> hide symbols when building 3pp code

- torchtext/experimental/datasets/sst2.py
Merge [commit](https://github.com/pytorch/text/commit/72236500b43151d8e2611a32aadbf6d9b4ad5cfa) from fbsync to main
> Fixing typing issues DataSet -> DataType

- docs/requirements.txt
per https://github.com/pytorch/vision/issues/4832#issuecomment-957695788
> fix CI docs build

- torchtext/datasets/sogounews.py
> migrate SogouNews to datapipes.

- torchtext/datasets/dbpedia.py
I'll wait for #1498 or #1499 to land before marking this ready so I can rebase the test changes. 
> migrate DBPedia to datapipes.

- torchtext/datasets/yahooanswers.py
Migrates dataset in `torchtext/datasets/`
> migrate YahooAnswers to datapipes.

- torchtext/datasets/yelpreviewfull.py
Migrates dataset in `torchtext/datasets/`
> migrate YelpReviewFull to datapipes.

- torchtext/datasets/yelpreviewpolarity.py
Migrates dataset in `torchtext/datasets/`
> migrate YelpReviewPolarity to datapipes.

- .circleci/config.yml
- .circleci/config.yml.in
> Pythorch 1.10.2 release

- torchtext/datasets/yelpreviewpolarity.py
> add double caching for yelp polarity to speed up extracted reading.

- torchtext/datasets/imdb.py
Migrate IMDB dataset to use torchdata datapipes
Test:
`pytest test/data/test_builtin_datasets.py -k IMDB`
> Migrate IMDB to datapipes

- torchtext/datasets/yahooanswers.py
> add double caching for yahoo to speed up extracted reading.

- torchtext/datasets/wikitext2.py
Migrate WikiText2 to datapipes and add secondary caching
Reference Issue: #1494 and #1526
```
pytest  test/data/test_builtin_datasets.py -v
```
> Migrate WikiText2 to datapipes

- torchtext/datasets/yelpreviewfull.py
> add double caching for yelp full to speed up extracted reading.

- torchtext/datasets/yelpreviewpolarity.py
This PR fixes the issue with dataset extraction caching
> [BUG-FIX] fix yelp dataset

- torchtext/datasets/yahooanswers.py
This PR fixes issue with yahoo dataset extraction caching
> [BUG-FIX] fix yahoo dataset

- test/datasets/test_agnews.py
> mock up AG NEWS test for faster testing.

- test/datasets/test_agnews.py
> remove extra print

- test/datasets/test_penntreebank.py
Reference Issue: https://github.com/pytorch/text/issues/1493
Added mocked unit test for PennTreebank dataset
`pytest test/datasets/test_penntreebank.py`
> Add PennTreebank Mocked Unit Test 

- test/datasets/test_yahooanswers.py
Reference Issue: https://github.com/pytorch/text/issues/1493
Added mocked unit test for YahooAnswers dataset
`pytest test/datasets/test_yahoo_answers.py`
> Add YahooAnswers Mocked Unit Test #1574

- test/datasets/test_agnews.py
- Renamed ag_news dataset variable name from `temp_dataset_dir` to `base_dir` to be consistent with other tests
> [MINOR] Renamed AG_NEWS variable name to base_dir

- torchtext/datasets/dbpedia.py
Reference Issue: https://github.com/pytorch/text/issues/1589
- Follow up to https://github.com/pytorch/text/pull/1500 to add caching for extracted files
> Added caching to extracted files in DBPedia

- test/datasets/test_wikitexts.py
Reference Issue: #1493
- Merge mocked unit test for WikiText103 and WikiText2 datasets
- ` pytest test/datasets/test_wikitexts.py`
> Add WikiText103 and WikiText2 Mocked Unit Tests

- torchtext/datasets/ag_news.py
- torchtext/datasets/amazonreviewfull.py
- torchtext/datasets/amazonreviewpolarity.py
- torchtext/datasets/cc100.py
- torchtext/datasets/conll2000chunking.py
- torchtext/datasets/dbpedia.py
- torchtext/datasets/enwik9.py
- torchtext/datasets/imdb.py
- torchtext/datasets/iwslt2016.py
- torchtext/datasets/iwslt2017.py
- torchtext/datasets/multi30k.py
- torchtext/datasets/penntreebank.py
- torchtext/datasets/sogounews.py
- torchtext/datasets/squad1.py
- torchtext/datasets/squad2.py
- torchtext/datasets/udpos.py
- torchtext/datasets/wikitext103.py
- torchtext/datasets/wikitext2.py
- torchtext/datasets/yahooanswers.py
- torchtext/datasets/yelpreviewfull.py
- torchtext/datasets/yelpreviewpolarity.py
- Updated formatting for all datasets using `black`
> [FORMATTING] Updated formatting for all datasets

- torchtext/datasets/ag_news.py
- torchtext/datasets/amazonreviewfull.py
- torchtext/datasets/amazonreviewpolarity.py
- torchtext/datasets/dbpedia.py
- torchtext/datasets/imdb.py
- torchtext/datasets/penntreebank.py
- torchtext/datasets/sogounews.py
- torchtext/datasets/wikitext103.py
- torchtext/datasets/wikitext2.py
- torchtext/datasets/yahooanswers.py
- torchtext/datasets/yelpreviewfull.py
- torchtext/datasets/yelpreviewpolarity.py
Reference issue: https://github.com/pytorch/text/issues/1588
Added docs for the following datasets
- Text Classification
- AG_NEWS
- SogouNews
- DBpedia
- YelpReviewPolarity
- YelpReviewFull
- YahooAnswers
- AmazonReviewPolarity
- AmazonReviewFull
- IMDb
- Language Modeling
- WikiText-2
- WikiText103
- PennTreebank
> [DOCS] Added docs for text classification and language modeling datasets

- .circleci/config.yml
- .circleci/regenerate.py
- packaging/pkg_helpers.bash
Build and test for Python 3.10
> Build and test py3.10

- torchtext/utils.py
> Change logging to use module level logger

- torchtext/_download_hooks.py
- torchtext/datasets/ag_news.py
- torchtext/datasets/amazonreviewfull.py
- torchtext/datasets/amazonreviewpolarity.py
- torchtext/datasets/cc100.py
- torchtext/datasets/conll2000chunking.py
- torchtext/datasets/dbpedia.py
- torchtext/datasets/enwik9.py
- torchtext/datasets/imdb.py
- torchtext/datasets/iwslt2016.py
- torchtext/datasets/iwslt2017.py
- torchtext/datasets/multi30k.py
- torchtext/datasets/penntreebank.py
- torchtext/datasets/sogounews.py
- torchtext/datasets/squad1.py
- torchtext/datasets/squad2.py
- torchtext/datasets/udpos.py
- torchtext/datasets/wikitext103.py
- torchtext/datasets/wikitext2.py
- torchtext/datasets/yahooanswers.py
- torchtext/datasets/yelpreviewfull.py
- torchtext/datasets/yelpreviewpolarity.py
This change is required to do monkey patching for internal datasets access (similar to SST2 dataset)
> Update download hooks and datasets to import HttpReader and GDriveReader from download hooks

- test/data/test_modules.py
- test/models/test_models.py
- test/test_functional.py
Added more tests for raise/log cases and few untested functions in:
- `torchtext.nn.modules.multiheadattention.py`
- `torchtext.models.roberta.bundler.py`
- `torchtext.functional.py`
Following stats in [codecov.io/gh/pytorch/text](https://app.codecov.io/gh/pytorch/text).
> Add more test coverage

- README.rst
- Adding more clarification around installing LTS binary distribution as a followup from #1662
> Update README around installing LTS version

- README.rst
- test/common/parameterized_utils.py
- test/data/test_modules.py
- test/models/test_models.py
- test/test_functional.py
- Improve tests (given comments in #1653)
- Sanitize test names generated by `@nested_params` (creating issues in `fbcode`)
> Resolve issues in #1653 + sanitize test names generated by nested_params

- docs/requirements.txt
> Pin Jinja2 version to fix broken doc build

- README.rst
- test/models/test_models.py
- Fixing formatting for all files to ensure CI lint job passes
> Fixed formatting for all files using pre-commit

- requirements.txt
> update requirements.txt for unit-testing

- torchtext/data/datasets_utils.py
Summary: Integrate with torch to run the training in local or flow
Reviewed By: Nayef211
Differential Revision: D35412165
fbshipit-source-id: 297bea540ace67d93965e0982d6c8f8ff5d03208
> [fbsync] torchx integration

- benchmark/benchmark_roberta_model.py
- benchmark/utils.py
Adding RoBERTa/XLM-R model benchmarks:
* Model forward
* Model forward/backward
As we made changes in the underlying model implementation, it is good to have the benchmark to track the performance gains/gaps. For instance, we recently migrated to BetterTransformer implementation and this benchmark can be used to assess the performance gains.
> Model benchmark

- examples/tutorials/sst2_classification_non_distributed.py
As it was pointed out in this comment:
https://github.com/pytorch/text/issues/1716#issuecomment-1124766084
> Updating sst2 tutorial to replace lambda usage

- test/datasets/test_qqp.py
Remove `print` statements added in #1713 within the test file.
> Delete prints in test_qqp.py

- .github/workflows/build-m1-binaries.yml
- packaging/build_conda.sh
- packaging/build_wheel.sh
- packaging/pkg_helpers.bash
Refactor TorchText version handing and adding first version of M1 builds
> Refactor TorchText version handing and adding first version of M1 builds

- .github/workflows/build-m1-binaries.yml
- packaging/pkg_helpers.bash
* Add m1 tagged build for torchtext
* Remove default chanell
* prettier
> Add m1 tagged build for torchtext (#1776)

- .github/workflows/build-m1-binaries.yml
Fix typo in nightly m1 ref
See: https://github.com/pytorch/vision/pull/6158
> Fix typo in nightly branch ref (#1783)

- docs/source/datasets.rst
> sharing -> sharding

- .github/workflows/build-m1-binaries.yml
Making sure we build correctly against release branch
Ref: https://github.com/pytorch/vision/pull/6168
> Making sure we build correctly against release branch

- .github/workflows/build-m1-binaries.yml
- packaging/pkg_helpers.bash
Adding the conda builds for m1
> Adding the conda builds for m1

- .github/workflows/build-m1-binaries.yml
- packaging/pkg_helpers.bash
* Adding the conda builds for m1
* Fix alignment
* Don't use mkl on arm64
* prettier
> Adding the conda builds for m1 (#1794)

- benchmark/benchmark_torcharrow_ops.py
- Add benchmark comparison code for TA ops: `add_tokens`
- Followup to https://github.com/pytorch/text/pull/1801
All times are for SST2 train dataset on MacBook Pro
```
torchtext's add tokens operation (string): 0.382
torchtext's add tokens operation (int): 0.431
torcharrow's add tokens operation (string): 3.652
torcharrow's add tokens operation (int): 0.075
```
- add_tokens operation on strings are ~10x slower on torcharrow
- add_tokens operation on ints are ~5x faster on torcharrow
> Adding benchmarks for add_tokens operator

- README.rst
- Update compatibility matrix for 0.13 release
- Once approved, I'll merge this right before the release
> [MERGE AT RELEASE] Update compatibility matrix for 0.13 release

- docs/source/transforms.rst
- torchtext/transforms.py
- Updating docs for regex tokenizer to include 
- caveats with RE2 regex library
- tokenization example with a single regex pattern
- Adding the tokenizer to generated docs
> [Docs] Updating usage docs for Regex Tokenizer

- examples/data_pipeline/roberta_dataframe.py
This PR updates example to use TA functional for adding tokens to the beginning and end of input.
> Use TA functional for adding tokens to the beginning and end of input

- benchmark/benchmark_torcharrow_ops.py
This PR adds the tensor creation operation to the TA ops benchmark code.
Running on MacBook pro for SST2 dataset with 67349 rows with average number of tokens per row is 11.35.
Torchtext  tensor creation process: ~1.19 sec
TorchArrow tensor creation process: ~21.91 sec
> Add TA  Tensor creation  operation to the benchmark

- examples/torcharrow/roberta_sst2_training_with_torcharrow.py
Addresses https://github.com/pytorch/text/pull/1808#discussion_r927018417
> Convert TA transform module to prepoc function

- .circleci/unittest/linux/scripts/environment.yml
- .circleci/unittest/windows/scripts/environment.yml
- requirements.txt
* Remove sphinx_rtd_theme from requirements.txt
* Removing other sphinx dependencies from unittests
> [cherry-pick] Remove sphinx_rtd_theme from requirements.txt (#1837)

- CMakeLists.txt
- build_tools/setup_helpers/extension.py
- torchtext/csrc/CMakeLists.txt
* Fixing build when cuda torch is installed
* Passing in TORCH_INSTALL_PREFIX from extension.py
> [cherry-pick] Fixing build when CUDA enabled torch is installed (#1814)

- .github/workflows/build-m1-binaries.yml
- packaging/pkg_helpers.bash
Switches to use our new AWS self hosted runners for Apple Silicon
> ci: Use self hosted runners for build

- torchtext/prototype/models/t5/wrapper.py
Change hardcoded module path in comments to be dynamic.
> Make comment paths dynamic

- packaging/pkg_helpers.bash
Fix upload channel using correct flag so that we don't need to change it when we switch between nightly/test channel
> [CI] Fix upload channel 

- packaging/pkg_helpers.bash
* Fix upload channell using correct flag
* Fix version extraction
> [CI] Fix upload channel  (#1932)

- packaging/pkg_helpers.bash
This reverts commit 00267737e2214e1b01ebc8b2cf68a2d9038407a0.
> Revert "[CI] Fix upload channel  (#1932)"

- packaging/pkg_helpers.bash
Change upload channel for release
> [CI] Change upload channel for release

- test/torchtext_unittest/datasets/test_cnndm.py
- torchtext/datasets/cnndm.py
- torchtext/datasets/imdb.py
- torchtext/datasets/iwslt2017.py
* Fixed on_disk_cache issues
[ghstack-poisoned]
* Update on "Fixed on_disk_cache issues"
Fixed issues with cache locks and cache files overwrites. Required to be compatible with https://github.com/pytorch/data/pull/810
[ghstack-poisoned]
* Update on "Fixed on_disk_cache issues"
Fixed issues with cache locks and cache files overwrites. Required to be compatible with https://github.com/pytorch/data/pull/810
[ghstack-poisoned]
> Fixed on_disk_cache issues (#1942)

- .github/workflows/build-linux-conda.yml
Like https://github.com/pytorch/text/pull/1956 but for conda workflows.
> [Nova] Add caller workflow for Linux Conda Builds

- .github/workflows/test-linux-cpu.yml
Adding a GitHub Action to run Linux CPU Unittests.
> [Nova] Linux CPU GHA for Unittests

- .github/workflows/test-macos-cpu.yml
This should be unblocked after https://github.com/pytorch/test-infra/pull/968 is merged.
> [Nova] Mac x86 Unittests

- README.rst
- Update compatibility matrix for 0.14 release
Closes #1980
> Update compatibility matrix for 0.14 release

- .github/workflows/validate-binaries.yml
> 2010 fix lint error

- CMakeLists.txt
Following the [change in PyTorch core](https://github.com/pytorch/pytorch/commit/87e4a087784c805312a2b48bb063d2400df26c5e) and [torchaudio](https://github.com/pytorch/audio/pull/2973)
> Update C++ Standard to 17

- test/smoke_tests/smoke_tests.py
- Add torchdata import and version checks (ensuring the nightly is within 3 days of the current date) to smoke tests
> [TEST] Add torchdata version to smoke tests

- .circleci/config.yml
- .circleci/config.yml.in
- packaging/pkg_helpers.bash
* Bump Versions
* Use test channel for uploads/builds
> [Release 0.15] Version Bumps and Update Channels

- .github/workflows/build-conda-linux.yml
- .github/workflows/build-conda-m1.yml
- .github/workflows/build-conda-macos.yml
- .github/workflows/build-wheels-linux.yml
- .github/workflows/build-wheels-m1.yml
- .github/workflows/build-wheels-macos.yml
Reverts pytorch/text#2066
This is supposed to be a release branch only change, reverting
> Revert "Channel=test for build matrix generation"

- .circleci/config.yml
- .circleci/config.yml.in
- packaging/install_torchdata.sh
- packaging/pkg_helpers.bash
- test/smoke_tests/smoke_tests.py
Bump Versions
Use test channel for uploads/builds
> Version Bumps and Update channels (#2067)

- .github/scripts/validate_binaries.sh
- .github/workflows/validate-nightly-binaries.yml
- test/smoke_tests/smoke_tests.py
Fix validation workflow for test chan, fix conda installs for 3.11
> Fix validation workflow for test channel

- .github/scripts/validate_binaries.sh
Use index-url for torchtext installs
> Use index-url for torchtext installs

- .circleci/config.yml
- .circleci/regenerate.py
> [cherry-pick] [0.15] Turn of circleci 3.11 unit tests (#2078)

- .github/workflows/test-linux-cpu.yml
- .github/workflows/test-linux-gpu.yml
- .github/workflows/test-macos-cpu.yml
Same as: https://github.com/pytorch/audio/pull/3115
> [Release only fix] fix unit tests

- examples/tutorials/t5_demo.py
See title and https://github.com/pytorch/tutorials/pull/2223
> Update tutorial to match PyTorch main tutorials page

- test/torchtext_unittest/common/torchtext_test_case.py
- test/torchtext_unittest/test_build.py
> Add decorator to skip tests and log a warning if URL is unaccessible

- setup.py
Update author and author email to match that in PyTorch core.
> Update author and author email

- examples/tutorials/t5_demo.py
Updating the title to fix the error in the doc build.
> Fix title underline

- README.rst
- torchtext/transforms.py
Fixes Link in README to `transforms` and completes list of available tokenizers.
> Small fixes in Readme

- .circleci/config.yml
- .circleci/config.yml.in
- .github/scripts/validate_binaries.sh
- packaging/build_conda.sh
Remove temporary channel python 3.11
> Remove temporary channel python 3.11

- .github/workflows/build-conda-windows.yml
- .github/workflows/build-wheels-windows.yml
> [Nova] Add windows workflows 

- .circleci/config.yml
- .circleci/config.yml.in
- .github/workflows/lint.yml
- .pre-commit-config.yaml
Lint Jobs to Nova. Removing the old jobs from CCI.
> [NovaX] Lint Job on GHA

- packaging/cut_release.sh
TSIA.  The script is copied from vision/audio.  I use this to cut `release/0.17` branch https://github.com/pytorch/text/commits/release/0.17
> Add script to do branch cut release

- .github/workflows/build-wheels-linux.yml
- .github/workflows/build-wheels-m1.yml
- .github/workflows/build-wheels-macos.yml
- .github/workflows/build-wheels-windows.yml
Cherry pick https://github.com/pytorch/text/pull/2220 to fix wheel build after the recent OIDC update.
> [oidc] switch text wheels to oidc (#2220)

- .github/workflows/build-conda-m1.yml
- .github/workflows/build-wheels-m1.yml
> Update labels for m1 runners
