requirements.txt
`test/snli.py` uses both `nltk` and `requests` but neither are in `requirements.txt`. Most importantly, `requests` is core to retrieving many of the datasets. Without these in `requirements.txt` users will experience ModuleNotFoundError errors.
=> Add `nltk` and `requests` to `requirements.txt`

torchtext/data.py, torchtext/datasets/snli.py
Adds the functionality I use in https://github.com/jekbradbury/examples/blob/spinn/snli/spinn.py, which creates shift+reduce parser transitions from the parse trees provided by SNLI. Also fixes #13.
=> Trees and fixes for SNLI

torchtext/data.py
For python 2.*, if the dataset contains special tokens, there are encoding errors to read the files.
A better way to fix this problem is to add an argument to indicate the encoding of the input file.
=> utf-8 encoding

torchtext/data.py
Allow fields to use a different pad token than `<pad>`, especially useful if the field is already numericalized or non vocabulary-based.
=> Parameterize pad_token

build_tools/travis/install.sh, test/data/test_field.py, torchtext/data/__init__.py, torchtext/data/field.py, torchtext/data/utils.py
This PR adds tests for the relatively simple `Field` methods  `Field.pad` and `Field.preprocess` -- the others are a bit more involved (you'd need to create `Dataset`s to properly test them), so I think I want to go "from the ground up" and write the tests for `Dataset` / other things that this uses before coming back to finish it.
This PR also adds some input validation to `get_tokenizer` and moves the get_tokenizer function into `data.utils` (though its still accessible from `data.get_tokenizer`, so nothing should break)
In general, let me know if there are datatypes that these methods should accept but I do not test; it's a bit hard to infer at times what the intended input is.
=> Add tests for simple Field methods

.gitignore, build_tools/travis/install.sh, test/data/test_field.py, test/data/test_utils.py, torchtext/data/example.py, torchtext/data/utils.py
Fixes #53 , adds the NLTK port of the Moses tokenizer. You can access it by passing the string`"moses"` to the `tokenize` argument of the `Field` constructor.
=> Add NLTK Moses tokenizer

torchtext/data/field.py
Should fix the problem described in #48.
=> switch encoding for py2 preprocessing to UTF-8

torchtext/data/iterator.py
In one place I left an old (and now wrong) default for `batch_size_fn`; this PR fixes that.
It also changes the `batch_size_fn` API to take three arguments rather than one. This is intended to support the ability to use the total number of tokens in a batch (`max_len * num_examples`) as an effective batch size in addition to the number of non-padding tokens `sum(len(ex) for ex in batch)` (in some cases the former is the relevant quantity when it comes to memory use, in some cases it's the latter). I strongly suspect no one else is using that API right now, but this is slightly breaking if they are.
=> fix and improve dynamic batching support

torchtext/data/field.py
This should fix #64 -- the LM dataset calls `Example.fromlist` on data that's already tokenized, so `Field.preprocess` needs to skip tokenization.
=> Fix Field.preprocess for LM dataset

torchtext/data/__init__.py, torchtext/data/iterator.py
Implements `state_dict` and `load_state_dict` methods on `Iterator` instances in order to load/save checkpoints that maintain the shuffling order, including with `BucketIterator`. This required a more deterministic way to keep track of RNG states and reproduce them with the `RandomShuffler` class.
=> Savable iterator

requirements.txt, test/trec.py, torchtext/datasets/__init__.py, torchtext/datasets/trec.py
```
import torch
from torchtext import data
from torchtext import datasets
inputs = data.Field(lower=True, include_lengths=True, batch_first=True)
answers = data.Field(sequential=False)
print('Generating train, dev, test splits')
train, test = datasets.TREC.splits(inputs, answers)
print(train[0].text, train[0].label)
```
yields
```
Generating train, dev, test splits
['how', 'did', 'serfdom', 'develop', 'in', 'and', 'then', 'leave', 'russia', '?'] DESC
```
When `fine_grained=True`:
```
Generating train, dev, test splits
['how', 'did', 'serfdom', 'develop', 'in', 'and', 'then', 'leave', 'russia', '?'] DESC:manner
```
Let me know if there is anything else you'd like to see. I'll leave the WIP until I hear 
back.
=> [WIP] TREC dataset

torchtext/data/iterator.py
**Intended effect:**
- `rnn.pack_padded_sequence` requires that a minibatch be sorted by decreasing order.
- Curriculum learning requires that the batches are sorted in increasing order.
**Proposed Solution:**
Flip the sign of the `self.sort_key(x)` when creating the Batch.
=> Batch should be sorted by decreasing size.

.travis.yml, torchtext/data/field.py
This PR adds Python 3 linting to the test matrix, and fixes an infraction (`unicode` type doesn't exist in python 3).
=> Run linter on python 3 on CI

codecov.yml
I noticed that codecov is considering the `test/` directory in coverage statistics since there's a bit of source code in there --- this tells codecov to ignore the folder.
=> Ignore tests directory in codecov statistics

torchtext/data/field.py
The `Field`'s `tokenize` argument takes a function to tokenize a string with. However, we also allow the user to pass in the string `spacy` to use the SpaCy english tokenizer. This wasn't mentioned in the docstring, so I added it.
=> Document spacy tokenization in Field tokenize argument

.travis.yml
When i set up the matrix initially, it was my intention to mirror the versions used in the PyTorch repo.  Looks like PyTorch is now testing on Python 2.7.9 instead of Python 2.7.8 (https://github.com/pytorch/pytorch/pull/2214), so making the same change here.
=> Update CI matrix to use Python 2.7.9 from 2.7.8 (parity with PyTorch)

test/common/torchtext_test_case.py, test/data/test_dataset.py, test/data/test_field.py, test/data/test_utils.py, torchtext/data/dataset.py, torchtext/data/example.py
This PR adds some tests to the `Dataset` and `Example` classes. It also sets up a `TorchtextTestCase` base test case class that is used as a central repository for writing synthetic test data to a temporary directory when running tests.
I've also made a few minor changes to the class behavior:
1.  Previously the dataset code would silently skip input fields that didn't exist in the JSON data. I'm curious if there's a real dataset that this makes easier to work with --- it certainly seems like it could be a pretty big source of bugs for the user, so I've changed it to error when the dataset tries to read a JSON key not actually in the data.
2. Reading CSV data with Unicode characters previously didn't work with Python 2, since the `csv` module in python 2 doesn't support unicode input. …
=> Dataset fixes and tests

test/data/test_pipeline.py, torchtext/data/pipeline.py
This PR fixes a few bugs in `data.Pipeline`, adds docstrings, and adds tests.
Bugfixes:
- `Pipeline.__call__` was accepting positional args, but wasn't forwarding them to `Pipeline.call`
- In `Pipeline.call`, we were running `self(token)` for each `token` in an input list, which has the effect of running the _entire pipeline_ on each token of the list. We were correctly executing only the current pipeline's `convert_token` if the input was not a list. This becomes a bug when you run a chained pipeline and the same step is executed multiple times.
Enhancements:
- `Pipeline.add_after` and `Pipeline.add_before` now return a reference to the Pipeline (so people don't run into errors doing `pipe = pipe.add_*(something)`)
- Add a check to ensure that the pipeline's input `convert_token` is …
=> Pipeline bugfixes, docstrings, and tests

torchtext/data/iterator.py
Fixes #109 by coercing the pad amount to int before copying the list.
=> Fix padding in Iterator for Python 2

test/imdb.py, test/sst.py, test/test_vocab.py, test/trec.py, torchtext/vocab.py
Depends on https://github.com/pytorch/text/pull/102.
Allows users to use custom embeddings (https://github.com/pytorch/text/issues/100).
Refactor to simplify Vectors.
=> Custom vectors and refactor

.travis.yml
I've noticed that the builds have been failing due to memory issues. As a result, I'm making the python 3 slow test environment non-container-based for more memory (it now matches the slow python 2 tests).
=> Make travis slow python3 environment sudo-required

test/common/torchtext_test_case.py, test/data/test_field.py, torchtext/data/field.py
This PR is a continuation of #47 and finishes testing the various functions for the field class (`build_vocab` and `numericalize`).
I also wanted to fix #78 and add a test for it, but I'm unsure how to properly do this. One way would be to simply convert the numerical features to python ints dictated by the input `tensor_type` member (e.g. `int` for `LongTensor`, `float` for `FloatTensor`, etc). This feels pretty brittle, does anyone else have any other suggestions?
=> Finish tests for Field class

torchtext/datasets/translation.py
Main branch code fails to compile when MT data is downloaded for the first time. This should fix the bug.
=> bug correction: fd_org should be in read mode in order to read lines

requirements.txt, setup.py, torchtext/data/dataset.py, torchtext/datasets/__init__.py, torchtext/datasets/imdb.py, torchtext/datasets/language_modeling.py, torchtext/datasets/translation.py, torchtext/datasets/trec.py, torchtext/utils.py
Also adds nonoptional dependencies to setup.py so `pip install torchtext` will fetch them.
The only known possibly-breaking change (I'd call it a bugfix) is that `Dataset.splits` will now use `os.path.join` rather than concatenation to join provided paths.
=> Fix WT2, restructure splits, and add WMT14

test/data/test_field.py, torchtext/data/__init__.py, torchtext/data/batch.py, torchtext/data/field.py
* Issue #141
* Field becomes subclass of RawField
* Normalized signatures of postprocessing
=> Added RawField that represents any datatype.

torchtext/datasets/snli.py, torchtext/datasets/translation.py
The current SNLI dataset class fails for the test case test/snli.py.  Even the SNLI example in [examples/snli](https://github.com/pytorch/examples/blob/master/snli/train.py#L22) fails. 
This should fix it.
=> bug fix: snli data loader

.gitignore, test/language_modeling.py, torchtext/datasets/language_modeling.py
I found that `wv_*` parameters are no longer used and cause errors.
So I updated the params and added tests to verify.
=> update wordvector parameters for language modeling and add tests

torchtext/vocab.py
GloVe twitter embedding has an improperly specified dimension.
=> Fix minor bug in GloVe aliases

torchtext/vocab.py
Using the input list ``specials'' 's memory is dangerous, which would cause bugs for the external code (difficult to debug).
=> allocate new list for self.itos

torchtext/data/iterator.py
This PR resolves #137.
Currently, `__len__` is implemented by:
```
def __len__(self):
return math.ceil((len(self.dataset[0].text) - 1) /
(self.batch_size * self.bptt_len))
```
This is insufficient, since "substraction by 1" should be performed in a batch-level.
=> Re-fix #137

torchtext/data/dataset.py
This actually does the opposite of what's proposed in #185, because any behavior that materializes a dataset that was meant to be lazy is a bug.
=> Keep generator in Dataset() even with filter_pred

.gitignore, README.md, docs/source/data.rst, requirements.txt, test/data/test_field.py, torchtext/data/__init__.py, torchtext/data/field.py
This PR mostly addresses #124 by introducing a nested field: a field that can contain another field. Please see `NestedField` class docstring for more info and `TestNestedField` class in `test/test_field.py` for examples. A complete list of what's introduced in this PR:
* Implement a `NestedField` class. This class implements a custom `preprocess`, `pad`, `build_vocab`, and `numericalize` method. The `pad` method is especially hacky since it uses monkeypatching. Unfortunately I can't think of any other idea. Suggestions for a more elegant approach are welcomed.
* Add `Sphinx` and `sphinx_rtd_theme` to `requirements.txt` to allow building docs locally.
* Put installation instructions in README, including the optional requirements (which is not optional if you want to run tests). Without …
=> Implement a nested field

test/data/test_field.py, torchtext/data/field.py
As discussed in #197, `NestedField` assumes that the nesting field is not another `NestedField`. This PR introduces a check for that. An error is raised when the assumption is violated.
=> Prevent `NestedField` to have another `NestedField` as nesting field

test/common/torchtext_test_case.py, test/data/test_dataset.py, torchtext/data/dataset.py, torchtext/data/example.py, torchtext/utils.py
I've made the TabularDataset class handle csv and tsv files using the standard csv library in Python. This should resolve the bugs surrounding newlines within the text (and probably some more hidden ones that are covered by the standard library).
I've added a unit test, run flake8 and confirmed the tests pass in both Python 2.7 and 3.6. If there's anything else I should do, please let me know:)
=> Fix TabularDataset failing for files with newlines in the text (#210)

test/common/torchtext_test_case.py, test/data/test_dataset.py, torchtext/data/dataset.py, torchtext/data/example.py, torchtext/utils.py
Now, fields can be specified like
```python
>>> pos = data.TabularDataset(
...    path='train.csv', format='csv',
...    fields={'labels': ('labels', data.Field(sequential=False)),
...                'text': ('text', data.Field(lower=True))}
...
```
=> Add option to use dict to specify fields for csv/tsv files (Fix # 215) 

torchtext/datasets/imdb.py
Using `pytorch` with `fast.ai` and not correctly configured Linux system leads to this kind of errors:
The code used
```
torchtext.datasets.IMDB.splits(TEXT, IMDB_LABEL, '/tmp/')
```
The error that is shown:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 796: 
ordinal not in range(128)
```
Adding the correct encoding in the open statement solve this problem.
More information here:
http://forums.fast.ai/t/imdb-test-data-is-different-from-what-is-shown-in-the-class/8138/13
=> Error with the encoding on python 3

test/data/test_dataset.py, test/sequence_tagging.py, torchtext/data/dataset.py, torchtext/data/example.py
With this change we can now pass a nested tuple to map a single data column to multiple fields (e.g. when we need both word and character embeddings):
```
WORD = data.Field(init_token="<bos>", eos_token="<eos>")
CHAR_NESTING = data.Field(tokenize=list, init_token="<bos>", eos_token="<eos>")
CHAR = data.NestedField(CHAR_NESTING, init_token="<bos>", eos_token="<eos>")
fields = [(('word', 'char'),(WORD, CHAR)), (None, None), ('ptbtag', PTB_TAG)]
train, val, test = datasets.UDPOS.splits(fields=fields)
```
Files modified:
* *torchtext/data/example.py*: Added code to process nested name-Field tuples
* *torchtext/data/dataset.py*: Added code to unpack Field tuples in Field dict
* *test/data/test_dataset.py*: Added testcase to test multiple fields in a CSV file
* *test/sequence_tagging.py*: …
=> Add support for multiple fields per single data column

test/data/test_field.py, torchtext/data/__init__.py, torchtext/data/field.py
- Added a LabelField subclass of Field that forces `sequential=False` and `unk_token=None`
- Added the LabelField to `__init__.py`
- Added some rudimentary tests (comparison of modified stoi/itos and field checks)
Two things that could be modified, but are not for the sake of simplicity:
- Print a warning message when user passes either of the arguments with values different than the forced ones
- throwing a ValueError seemed like an overkill due to intuitiveness, so currently the constructor silently overwrites the arguments (which could be bad tbh)
- Modify '__setattr__' to deny modifications of those fields
- seemed like something that should be left to the user
=> Add label field

torchtext/data/iterator.py
Fixes https://github.com/pytorch/text/issues/236 by setting device to CPU if torch can't detect CUDA. 
I wonder if any tests should be written for this?
=> Set device to CPU if CUDA is not available

test/data/test_field.py, torchtext/data/field.py
Motivated by Keras test preprocessing.
Using `truncate_first` parameter, we can truncate the sentence at the beginning or at the end.
=> Add truncate_first parameter to Field Constructor

torchtext/data/iterator.py
Fixes `BPTTIterator` for #244 and #256 
Also, `iter.epoch` was returning floats, so I floored this to integers since it's more intuitive. This can be reverted easily though if there is a not so obvious use-case.
=> Fix deprecated StopIteration, increment iterations in BPTTIterator, make epoch() return int

torchtext/datasets/language_modeling.py
I've noticed that WikiText-103 for language modeling wasn't available in the current codebase, so I added it, following the practices in` text/torchtext/datasets/language_modeling.py`. I've obtained the dataset through [this site](https://www.salesforce.com/products/einstein/ai-research/the-wikitext-dependency-language-modeling-dataset/) (word level).
=> Add WikiText-103 to lang. modeling datasets

test/data/test_field.py, torchtext/data/field.py
1. The sentence_length and word_length infomation couldn't be fetched from the origin NestedField, and i think the word_length infomation is useful to help us to get the right character rnn result through mask the rnn's output. In the new NestedField, the `include_lengths` parameter have beed added to the `__init__` method, using this parameter to determin whether return the `sentence_length` and `word_length` with `padded` mini-batch. 
2. fix the NestedField build_vocab method
=> add include_length para in NestedField

torchtext/vocab.py
If the user kills the script while downloading vectors, a
broken zip file will be left behind.  If the user tries to
create the same vocab later on, they will get an error about
a broken zip file and will have to manually clean up the file:
=> Delete partial zip file on keyboard interrupt

torchtext/utils.py
for some websites blocking user-agent used by urllib, we need to add header to download datasets from them, e.g. the facebook bAbI data
=> fixed http 403 forbidden error when downloading dataset

torchtext/data/iterator.py
Call to `pool` method failed due to a wrong argument name in #258 .
This should have failed tests and shouldn't have been merged as it breaks **every** BucketIterator called with `sort=False`, as reported in #271.
=> [Urgent] Fix argument to pool call

test/babi.py, torchtext/data/field.py, torchtext/datasets/__init__.py, torchtext/datasets/babi.py, torchtext/utils.py
there are three things in this PR:
1. enhanced build_vocab on three dimensional data input, for example, the story in shape of [batch_size, memory_size, seq_len] of bAbI dataset. #264 
2. added Facebook bAbI dataset and its test file
3. changed urllib to requests for downloading bAbI dataset.
=> added bAbI dataset

README.rst, build_tools/travis/install.sh, test/common/torchtext_test_case.py, test/data.py, test/data/test_batch.py, test/data/test_builtin_datasets.py, test/data/test_dataset.py, test/data/test_field.py, test/data/test_subword.py, test/imdb.py, test/language_modeling.py, test/sequence_tagging.py, test/snli.py, test/sst.py, test/translation.py, test/trec.py, torchtext/data/batch.py, torchtext/data/field.py, torchtext/data/iterator.py, torchtext/data/utils.py
#295
- Fixes volatile for pytorch 0.4 / 0.3 (with a version check)
=> [Breaking] Pytorch 0.4 release compatibility fixes

test/data/test_field.py, torchtext/data/field.py, torchtext/datasets/babi.py
the fixes to pytorch 0.4 compatibility issues stop creating cuda tensor due to:
```python
self.tensor_type(arr, device=device)
```
tensor_type is torch.LongTensor by default which doesn't accept a `device` argument. as suggested by [migration guide](http://pytorch.org/2018/04/22/0_4_0-migration-guide.html), i change it to `torch.tensor` for numericalization. 
pytorch 0.4 also decouples type, device, layout from creation of tensors. i changed `tensor_type` to `dtype`, because the tensor_type like `torch.LongTensor` explicitly creates a CPU dense tensor of type long, which means more than just a type.
=> [Bug Fix] numericalize doesn't create cuda tensor 

test/data/test_subword.py
[TestSubword](https://github.com/pytorch/text/blob/master/test/data/test_subword.py#L8) fails for python 2.7, making other tests not to run in recent PR's.
Since the problem seems to be external (revtok), this patch will skip the test for py2.7 so that the failing test does not stop patch and codecov.
=> Patch subword test failing in python 2.7

requirements.txt, test/data/test_utils.py, torchtext/data/utils.py
Moses tokenizer has been deleted from nltk because of a license issue.
The current build is broken because of this change.
This fix resolves #306 
Also added toktok tokenizer based on the suggestion from @alvations
=> migrate to sacremoses and add toktok tokenizer

test/data/test_field.py, torchtext/vocab.py
=> Fix vector dimension of OOV token (#275)

torchtext/data/dataset.py
Documentation says format can be passed in a case-insensitive way for tabular data sets, but this is not true. The if conditions compare unlowered format variable to lowercased 'csv' and 'tsv', etc.: `if format == 'csv':`. This PR fixes that.
=> TabularDataSet format fix

torchtext/vocab.py
* Add support for passing a `max_vectors` argument, in situations where the entire set of pre-trained vectors can't fit in memory (most pre-trained vector sets are sorted in the descending order of word frequency, so if you pass, say, `max_vectors=100_000`, you will get pre-trained for 100_000 most common words)
* Add ability to read pre-trained vectors from gzipped files (without tar)
* Read pre-trained vectors by iterating over the vectors file object line by line, without reading the whole file into memory first
* Only load the file in binary mode to make parsing logic more compact
* Make vector loading more memory-efficient (based on #298)
* Minor refactoring to improve style
=> Make vector loading more flexible.

README.rst
Couldn't find the documentation in the `readme.rst`, so I've added it.
=> Adding a link to the documentation

torchtext/datasets/translation.py
Should fix #312. Added path arguments to Multi30k and WMT14 splits.
=> Fix 'splits' functions of Multi30k and WMT14 datasets 

torchtext/data/dataset.py
Current `random_state` takes a tuple returned by `random.getstate()`, not `int` (See #336 ). So I fix the docstring.
=> Fix parameter's explanation in Dataset.split

test/translation.py, torchtext/datasets/translation.py
Fixes #384
The situation here is much more convoluted than necessary, and I don't like two path checks in a row.
=> Fix translation dataset splits errors

test/nli.py, torchtext/data/dataset.py, torchtext/datasets/nli.py
- Fix ParsedTextField postprocessing that still accepts three args instead of two
- Added an option for ParsedTextField to whether to reverse the sentence as postprocessing
- Include parse trees for testing and reverse postprocessing test
=> fixed ParseTextField postprocessing, added genre field to MultiNLI

torchtext/data/batch.py
When some fields in the `TabularDataset` were defined as `None` (to be skipped), the `getattr` call in `Batch.__str__` would fail for those fields.
=> Fix error with None fields

docs/source/conf.py, docs/source/vocab.rst, torchtext/vocab.py
- Remove pointer to `torch` (alike torchvision)
- Remove docs for `pretrained aliases` as they were causing the build to fail
- Escape underscores in `torch.tensor.zero_`
- Bump year
=> Docs fixes

test/data/test_field.py, torchtext/data/field.py
Feature implementation for #354 
Simply added option to pass stop words to a field during initialization and have it remove words during preprocessing. API is based on the [CountTokenizer from scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).
Stop words being an attribute of the field (not the vocab) seems natural when you consider the vocab as just a mapping from tokens to integers.
=> Feature to ignore tokens

torchtext/vocab.py
Fix #398 and use `max_size`. 
```
from torchtext.vocab import SubwordVocab
from collections import Counter
counter = Counter("torch torch test".split())
v1 = SubwordVocab(counter, max_size=10)
print(v1.itos, v1.stoi)
v2 = SubwordVocab(counter, max_size=10)
print(v2.itos, v2.stoi)
```
This version's output
```
['<pad>', 't', 'c', 'e', 'h', 'o', 'r', 's', 'torch', 'test', 'est'] defaultdict(<function _default_unk_index at 0x11bc13158>,
{'<pad>': 0, 't': 1, 'c': 2, 'e': 3, 'h': 4, 'o': 5, 'r': 6, 's': 7, 'torch': 8, 'test': 9, 'est': 10})
['<pad>', 't', 'c', 'e', 'h', 'o', 'r', 's', 'torch', 'test', 'est'] defaultdict(<function _default_unk_index at 0x11bc13158>,
{'<pad>': 0, 't': 1, 'c': 2, 'e': 3, 'h': 4, 'o': 5, 'r': 6, 's': 7, 'torch': 8, 'test': 9, 'est': 10})
```
=> Fix SubwordVocab

test/test_vocab.py, torchtext/vocab.py
Related to #322.
New argument can specify when do tokes in `specials` add into `itos` and `stoi` in `Vocab` class.
Example
```python
from torchtext.vocab import Vocab
from collections import Counter
counter = Counter("a a b b c c".split())
v = Vocab(counter, max_size=2, specials=['<pad>', '<eos>'])
print(v.stoi, v.itos)
v = Vocab(counter, max_size=2, specials=['<pad>', '<eos>'], specials_first=False)
print(v.stoi, v.itos)
```
Output
```python
defaultdict(<function _default_unk_index at 0x11cdb20d0>,
{'<pad>': 0, '<eos>': 1, 'a': 2, 'b': 3})
['<pad>', '<eos>', 'a', 'b']
defaultdict(<function _default_unk_index at 0x11cdb20d0>, 
{'a': 0, 'b': 1, '<pad>': 2, '<eos>': 3})
['a', 'b', '<pad>', '<eos>']
```
=> New argument to add special tokens after building vocab

torchtext/data/field.py
Otherwise, will get this error: 
```
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```
=> Make NestedField compatible with GPU

test/data/test_field.py, torchtext/data/field.py
I guess this PR fixes #372 .
In the currect code, `nestedField.vocab.freqs` and `nestedField.nesting_field.vocab.freqs` are empty.
1. `nestedField.vocab.freqs` is empty because `build_vocab()` does not have any argument in [this line](https://github.com/pytorch/text/blob/master/torchtext/data/field.py#L645).
1. `nestedField.nesting_field.vocab.freqs` is not empty in `build_vocab` function, but it becomes empty because [the current code]((https://github.com/pytorch/text/blob/master/torchtext/data/field.py#L651)) assigns `nestedField.vocab` to `nestedField.nesting_field.vocab`.
In this PR, `nestedField.nesting_field.vocab.freqs` is copyed into `nestedField.vocab.freqs` to access `nestedField.nesting_field.vocab.freqs`. 
Is it expected behavior?
If so, I will add test code to this PR.
=> Save nesting_field.vocab.freqs

test/data/test_dataset.py, torchtext/data/dataset.py
Handles issue #349 and also exposes additional attributes of `csv_reader` to the user of `TabularDataset` so that they can modify the handling of csv files as they see fit.
Any keyword arguments can now be passed to csv_reader through the `csv_reader_params` keyword argument.
=> Exposed parameters for csv reader to user through dataset

test/data/test_field.py, torchtext/data/field.py, torchtext/data/utils.py
- Add the option to serialize fields with `torch.save` or `pickle.dump`
- Add basic tests
- Allows tokenizers in different languages for spacy (argument `tokenizer_language`)
All lambdas were removed from the pipeline and replaced with closures / partials or explicit functions. The responsibility of a custom tokenizer being serializable is on the user. 
An ugly hack overcomes the problem of `torch.[dtype]` not being serializable.
=> Field serialization, tokenizers in different languages

torchtext/data/field.py
=> fix stop_words conversion to set

torchtext/data/field.py
Fixing issue potentially caused by #288. You can now use RawField directly without any workarounds as mentioned in issue 422.
=> Set `is_target` to False by default in `RawField`

torchtext/data/iterator.py
Transposes the text and target tensors if the text field has `batch_first` set to True.
=> Batch first for BPTTIterator

test/test_vocab.py, torchtext/vocab.py
Fix issue #447 by verifying if `<unk>` is not in specials list and then creates a defaultdict without default_factory.
=> Fix collisions between oov words and in-vocab words (#447)

torchtext/vocab.py
Previous URL has been returning 403 for quite a while now this new url seems to be working better.
=> fix dead url for fasttext vectors

README.rst
Change documentation based on https://github.com/pytorch/text/pull/361.
=> Update Moses Python Port Link

test/common/torchtext_test_case.py
Inplace ops on `.data` error out in newer versions of pytorch
=> remove `.data`  call

setup.py
A small patch to avoid copying `test/common` and `test/data` folders when `torchtext` is installed.
Currently one can find them at
```
ls <python>/site-packages/test/
> common  data
```
=> Avoid installation of `test` folder

torchtext/vocab.py
Hi all,
I notice that the Vocab uses the defaultdict but the default number is always 0. 
If I set specials_first=False, then the unk_index must be wrong;
If I set the specials=['\<eos\>', '\<sos\>', '\<pad\>', '\<unk\>'], then the unk_index is also wrong.
The correct way is to generate the unk_index according to the specials.
Best regards,
Xin Liu
=> Fix the hard code for the unk_index

.travis.yml
conda doesn't vendor every dependency (in this case 2.7.9).
It is still covered by python 2.7, which is linked to python 2.7.16 in conda package.
=> Drop travis CI tests on python 2.7.9.

torchtext/data/dataset.py, torchtext/data/iterator.py, torchtext/data/utils.py, torchtext/utils.py, torchtext/vocab.py
With some very basic APIs (download_from_url, extract_archive, build_dictionary, rationed_split, generate_ngrams), we hope to build new datasets directly from torch.utils.data.dataset. The existing abstract dataset class in TorchText (i.e. torchtext.data.Dataset) is too complicated. We hope to gain flexibility with this simplified pattern. A few supervised learning dataset will be implemented based on this new pattern. As more necessary APIs are added, we hope the new APIs allow a user to do everything they want to do.
Steps to build datasets with the new pattern:
- The download_from_url and extract_archive functions are used to download and extract the online raw data. 
- Some text preprocessors/processors (e.g. spaCy) are required to clean the data and tokenize the sentence. It should …
=> [WIP] add new APIs to build dataset

test/test_vocab.py, torchtext/vocab.py
Add __len and get_vecs_by_tokens functions to Vectors
I'm using torchtext to rewrite a GluonNLP-based program(https://d2l.ai/chapter_natural-language-processing/similarity-analogy.html)，I want to use the Vectors in a more flexible way. For example:
```python
def knn(W, x, k):
cos = nd.dot(W, x.reshape((-1,))) / (
(nd.sum(W * W, axis=1) + 1e-9).sqrt() * nd.sum(x * x).sqrt())
topk = nd.topk(cos, k=k, ret_typ='indices').asnumpy().astype('int32')
return topk, [cos[i].asscalar() for i in topk]
def get_similar_tokens(query_token, k, embed):
topk, cos = knn(embed.idx_to_vec,
embed.get_vecs_by_tokens([query_token]), k+1)
for i, c in zip(topk[1:], cos[1:]):  # 除去输入词
print('cosine sim=%.3f: %s' % (c, (embed.idx_to_token[i])))
def get_analogy(token_a, token_b, token_c, embed):
vecs = …
```
=> Add __len__ & get_vecs_by_tokens to Vectors

README.rst, docs/source/datasets.rst, test/data/test_builtin_datasets.py, torchtext/datasets/__init__.py, torchtext/datasets/text_classification.py
Add a few supervised learning datasets, including
- AG_NEWS
- SogouNews
- DBpedia
- YelpReviewPolarity
- YelpReviewFull
- YahooAnswers
- AmazonReviewPolarity
- AmazonReviewFull
=> [WIP] Add new datasets for text classification.

torchtext/utils.py
csv.field_size_limit input was changed from sys.maxsize to maxInt. This Will resolve the "OverflowError: Python int too large to convert to C"  error.
=> Fix the overflow error by changing maxInt

build_tools/travis/install.sh, test/data/test_utils.py
Fix the travis CI tests. Temporarily remove nltk downloader in travis CI tests. Need to push it back after the issue related to moses tokenizer is resolved. https://github.com/alvations/sacremoses/issues/61
=> Temporarily remove nltk downloader in travis CI tests

test/test_vocab.py, torchtext/vocab.py
(Hopefully) fixes the issue mentioned in #531, after the PR was merged.
Previous instances of "Vocab" didn't have the "unk_index" attribute, which the deserialization wrongly assumes will be present. This is causing issues when loading models stored with previous versions of torchtext. I added a bandaid fix as well as a test checking whether loading works on a mocked older version of the Vocab instance.
@francoishernandez I would appreciate if you can test the patch once it's merged.
=> Fix backwards compatibility of vocab serialization

examples/text_classification/train.py
- Corrected help string in argument parser for default epochs
- Added help string in argument parser for --save-model-path (same help string as in iterable_train.py in examples/text_classification)
=> Fix example argument help strings

docs/source/data/metrics.rst, test/data/test_metrics.py, torchtext/data/__init__.py, torchtext/data/metrics.py
A quick review of MT quality scores:
**[BLEU]( https://www.aclweb.org/anthology/P02-1040.pdf) (Bilingual Evaluation Understudy)**, also called N-Gram Co-Occurence, was developed by IBM in 2001. It is a measure of similarity between a candidate translation and a set of reference translations, where each reference translation is equally valid. The essence of it is the following: we check how many n-grams the candidate and reference translation have in common (up to 4-grams). The idea is to focus on *precision*: how much of my candidate translation has correct words? However, if we only relied on precision, the machine could only output one word and precision would be super high but the translation (and recall) very bad. That’s why BLEU adds a “brevity penalty” to penalize for too short …
=> Add BLEU score metric

README.rst, docs/source/legacy/datasets.rst, test/data/test_builtin_datasets.py, torchtext/__init__.py, torchtext/data/__init__.py, torchtext/data/functional.py, torchtext/datasets/language_modeling.py, torchtext/legacy/__init__.py, torchtext/legacy/datasets/__init__.py, torchtext/legacy/datasets/language_modeling.py
Re-write the language modeling datasets with a new pattern which was first applied for text classification datasets in v.0.4.0 release.
The motivation for the new pattern is to simplify data processing in Torchtext and grant users more flexibility to build the pipeline. There are three major issues we want to solve:
- Remove the dependency of `Field` class, which couples tokenizer, vocabulary, split, batching and sampling, padding, and numericalization together. It's like a "black box" and confuses users about what's going on inside it. Instead, with the new pattern, the components mentioned above should be some basic building blocks. Users can build the data processing pipeline with the orthogonal components.
- Incompatible with `DataLoader` and `Sampler` in `torch.utils.data`. Some …
=> Re-write language_modeling datasets (PennTreebank, WikiText103, WikiText2)

torchtext/datasets/text_classification.py
Fix #657 
The default value in the docs is 1.0.
=> Fix default ngrams in text classification datasets to 1.

README.rst
Leave a note in the README file and notify users the ongoing revamping work for torchtext library.
=> Readme note

test/test_utils.py, torchtext/data/functional.py, torchtext/datasets/unsupervised_learning.py, torchtext/experimental/datasets/language_modeling.py, torchtext/utils.py
Corrected behavior described in this [PR](https://github.com/pytorch/text/pull/688#issuecomment-582543743) 
Before this PR:
```python
import os
from torchtext.utils import extract_archive, donwload_from_url
os.mkdir('.data')
download_from_url('https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip')
extract_archive('.data/wikitext-2-v1.zip')
```
After this PR
```python
import os
from torchtext.utils import extract_archive, donwload_from_url
os.mkdir('.data')
download_from_url('https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip')
extract_archive('.data/wikitext-2-v1.zip')
```
**NOTE**: This PR is BC Breaking, if you are using this function to build custom datasets, there is no need to write code to join the root and extracted filenames. The outputted …
=> [Bug Fixing][BC Breaking] Unify tar and zip handling with extract_archive

docs/source/datasets.rst
Language Modeling part is duplicated at the start and between Entailment and Machine Translation
=> remove duplicate document in dataset

.flake8
Extend the allowable line length in flake8. Consistent with pytorch core library.
=> Allow longer line in flake8 for torchtext

README.rst
Since one of the dependency libraries `sentencepiece` is not distributed via conda, we advice users to install `sentencepiece` from `powerai` channel. Fix https://github.com/pytorch/text/pull/726
=> update README file for conda installation

torchtext/data/functional.py
Since sp is not released via conda, if users install torchtext's conda wheels, we don't force them to install sp until they use relevant API.
=> error out if sentencepiece is not installed

torchtext/datasets/text_classification.py
Fix a mistake in docs. Shift the labels of text classification datasets down by 1.
=> Update the labels of docs in text classification datasets

README.rst
The explicit target name "here" is duplicate. This causes error for pypi check `twine check dist/*`
=> Remove duplicate explicit target name in README.rst

.circleci/config.yml, .circleci/config.yml.in, .circleci/unittest/scripts/run_test.sh, test/common/test_markers.py, test/conftest.py, test/data/test_builtin_datasets.py, test/data/test_field.py, test/test_vocab.py
This PR adds caching mechanism for Circle CI unit tests.
- `.vector_caches` and `.data` directories are cached.
- `@slow` decorators (implementation and usage) are removed.
- CI job 45 mins without cache -> 7 mins with cache, which I believe is reasonable.
- Caches expire weekly. When we setup nightly job, new cache will be created on Sunday.
- Note: Circle CI does not provide mechanism to bust cache.
If one needs to refresh cache manually, update version string in cache key. 
such as `data-v1-{{ checksum ".circleci-weekly" }}` -> `data-v2-...`
- I also applied the same rule to `conda` environment cache.
- The resulting cache will be used by all the CI jobs, regardless of Python version, branch etc...
=> Add CCI cache for test data

torchtext/data/iterator.py
Fixes #376 
Points default device to torch cpu instead of None if no device is specified to be compatible with torch device types
=> use 'cpu' instead of None for Iterator

.circleci/unittest/scripts/environment.yml, .circleci/unittest/scripts/install.sh, .circleci/unittest/scripts/run_test.sh, .flake8, .gitmodules, build_tools/setup_helpers/__init__.py, build_tools/setup_helpers/extension.py, setup.py, test/data/test_functional.py, torchtext/__init__.py, torchtext/csrc/sentencepiece.cpp, torchtext/data/functional.py
This PR adds `torchscript` extension `_torchtext.so`, which contains simple interface to `SentencePiece`.
- SentencePiece `v0.1.86` is used.
- `libsentencepiece.a` is built right before `_torchtext.so` is compiled.
The logic for triggering this build from `setuptools` can be found under `build_tools/setup_helpers`.
- `_torchtext.so` provides interface to train a SentencePiece model and load a model from file.
- Our custom `SentencePiece` class has the following methods
- `Encode`
- `EncodeAsIds`
- `EncodeAsPieces`
- ~~is pickle-able **TODO** Add pickle/un-pickle test~~ This is not for simple pickling, but for `torchscrpit` serialization.
- Our custom `SentencePiece` class replaces the original `SentencePieceProcessor` class, which is the official Python binding using Swig.
- Due to the …
=> [BC breaking] Add Sentencepiece torchscript Extension

.circleci/unittest/scripts/environment.yml, requirements.txt
The latest version of flake8 added check for E741 and causing CI to fail.
This PR temporarily fix it by pinning the flake8 version.
```
./torchtext/datasets/translation.py:181:21: E741 ambiguous variable name 'l'
./test/common/torchtext_test_case.py:110:30: E741 ambiguous variable name 'l'
```
=> Temporary fix for flake8

torchtext/__init__.py
When building `torchtext` with buck, the path to `_torchtext.so` has to be normalized.
The fix was taken from [`torchvision`'s equivalent](https://github.com/pytorch/vision/blob/4e138bd5602d7e1b3713998ad213c5e1f16e25ce/torchvision/extension.py#L4-L20)
=> Fix extension import path for buck

README.rst
Preview: https://github.com/mthrok/text/blob/update-readme/README.rst
=> Update installation direction

torchtext/csrc/sentencepiece.cpp
See D21483116
> Passing a not noexcept-copyable type by value can lead to accidental copy failure.
> Pass the type by const reference.
> std::move called with const argument
> Variable content
> The result is const&&. This is probably not what you intended.
=> Resolve linter warning

test/common/assets.py, test/data/test_functional.py, test/data/test_utils.py
@cpuhrsch @zhangguanheng66 
It turned out that buck runs test in a directory of which full path contains a comma.
When Sentence Piece Trainer is given such a path, it considers there are multiple of paths, and fails.
To workaround this, I added a helper function that facilitates path generation and optionally copy the file to temporary directory and return the path there.
Then I adopted the function to other places where it uses test assets.
=> Add utility func to get path to assets

test/data/test_utils.py
Seems like the issue had been resolved. https://github.com/alvations/sacremoses/issues/61
Test run time: ~= 0.4 second.
=> Do not skip sacremoses tokenizer test

test/data/test_builtin_datasets.py, test/data/test_dataset.py, test/data/test_field.py, test/data/test_subword.py, test/data/test_utils.py, test/test_build.py, test/test_utils.py, test/test_vocab.py
Tests that require dataset (either via network access or cache) as following are moved to `test/test_build.py`.
```
test_vocab_vectors_custom_cache (test.test_vocab.TestVocab)
test_vocab_extend (test.test_vocab.TestVocab)
test_vocab_download_glove_vectors (test.test_vocab.TestVocab)
test_vocab_download_fasttext_vectors (test.test_vocab.TestVocab)
test_vocab_download_custom_vectors (test.test_vocab.TestVocab)
test_vocab_download_charngram_vectors (test.test_vocab.TestVocab)
test_vectors_get_vecs (test.test_vocab.TestVocab)
test_get_tokenizer_spacy (test.data.test_utils.TestUtils)
test_json_dataset_one_key_multiple_fields (test.data.test_dataset.TestDataset)
test_csv_file_no_header_one_col_multiple_fields (test.data.test_dataset.TestDataset)
test_build_vocab …
```
=> Separate tests which require external resource

test/data/test_utils.py, test/test_build.py
Follow up of #783 . `sacremoses` is not available in fbcode. This is the last piece.
=> Move `test_get_tokenizer_moses` to test_build

torchtext/csrc/sentencepiece.cpp
Fix for `fbcode autodeps`.
Although the header file `sentencepiece_processor.h` is included by `sentencepiece_trainer.h`, without explicitly including `sentencepiece_processor.h`, `autodeps` cannot find the dependencies properly.
=> Fix csrc header for autodeps

test/common/assets.py, test/data/test_functional.py
When multiple instances of test_generate_sp_model run,
intermediate model data have to be unique and properly cleaned up.
See also T67599333
=> Fix test_generate_sp_model for stress test

.circleci/config.yml, .circleci/config.yml.in
When running smoke test, proper way to install conda package is to install from workspace, instead of installing from archive. https://github.com/conda/conda/issues/1884 Otherwise the dependencies are not properly installed https://app.circleci.com/pipelines/github/pytorch/text/340/workflows/1a453eb2-4480-4f49-babf-34e5230697f2/jobs/4401/steps .
For this, we pass the whole `conda-bld` directory from conda package build job to upload job then smoke test job.
=> Install conda package from workspace

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py
Should run binary build and upload jobs on tags now and automatically
upload them to the right channel.
Similar to work done for https://github.com/pytorch/audio/pull/738, https://github.com/pytorch/vision/pull/2204
=> .circleci: Add functionality to run on tags

test/asset/vocab_test.txt, test/experimental/test_vocab.py, torchtext/experimental/vocab.py
- Removing `special` tuple from Vocab parameters since it's common that special tokens are defined in `ordered_dict`
- Refer to #890 for more info
=> Removing specials tuple from experimental Vocab

test/experimental/test_vocab.py, torchtext/csrc/vocab.cpp, torchtext/experimental/vocab.py
- Previously, `itos_` was not being updated when a token was inserted into the Vocab
- Also improved efficiency of offsetting token indices by 1 using `itos_`
- Updated tests to catch bug in the future
=> Fixing bug with vocab token insertion

benchmark/benchmark_experimental_vectors.py, torchtext/csrc/vectors.cpp
- Updating Vectors class to use order_preserving_flat_hash_map 
```
Construction time from file: 778.5076372753829
Construction time from cache: 4.878308408195153
Lookup time: 173.31978496885858
```
```
FastText Experimental
Construction time: 670.8132877256721
Construction time from cache: 39.3408519141376
FastText Experimental - Eager Mode
Lookup time: 113.68280134536326
FastText Experimental - Jit Mode
Lookup time: 224.18116508424282
```
```
Construction time: 824.6348864280153
Construction time from cache: 54.51048343884759
FastText Experimental - Eager Mode
Lookup time: 92.03254385315813
FastText Experimental - Jit Mode
Lookup time: 213.60061646718532
```
=> Updating cpp Vectors class to use order_preserving_flat_hash_map implementation

benchmark/benchmark_experimental_vectors.py, test/experimental/test_vectors.py, torchtext/csrc/vectors.cpp
- Updating Vectors class to use lazy view construction
- Fixed bug where the underlying `vectors_` tensor wasn't being updated on `__setitem__` calls 
- Updated tests to reflect new changes
- Reenabling `GloVe` and `FastText` tests
```
Construction time from file: 778.5076372753829
Construction time from cache: 4.878308408195153
Lookup time: 173.31978496885858
```
```
FastText Experimental
Construction time: 670.8132877256721
Construction time from cache: 39.3408519141376
FastText Experimental - Eager Mode
Lookup time: 113.68280134536326
FastText Experimental - Jit Mode
Lookup time: 224.18116508424282
```
```
Construction time: 781.7042375288438
Construction time from cache: 54.51048343884759
FastText Experimental - Eager Mode
Lookup time: 92.08985158009455
FastText Experimental - Jit …
```
=> Vectors lazy tensor view construction

.circleci/config.yml, .circleci/config.yml.in
Issues were arising when testing release candidates where we would
segfault based on binaries installed from an incorrect channel. This
makes it so that we install from the pytorch-test channel on tags
Similar to https://github.com/pytorch/audio/pull/859
=> .circleci: Only use the channel we want for test

test/experimental/test_vectors.py
- Disabling all glove tests due to URL breakage
- Refer to https://github.com/stanfordnlp/GloVe/issues/174
=> Disabling glove tests due to URL breakage

torchtext/experimental/datasets/text_classification.py
Fix issue https://github.com/pytorch/text/issues/941
=> fix typo in text classification get_labels() func

benchmark/benchmark_experimental_vocab.py
- Fixed mixing `to_ivalue()` call for benchmarking JIT vocab
=> Fixed JIT error with benchmarking vocab

.circleci/config.yml, .circleci/config.yml.in
Upstream is on 9.4.1 and we were experiencing issues when conda-build
was attempting to check for overlinking and failed out due to some files
not existing in xcode 9.0
Similar to https://github.com/pytorch/audio/pull/898
=> .circleci Bump xcode workers to 9.4.1

test/experimental/test_vectors.py, test/experimental/test_vocab.py, torchtext/experimental/vectors.py, torchtext/experimental/vocab.py
- Updating Vocab and Vectors classes to use `forward` instead of `__call__`
- Added unit tests to reflect changes
- Fix for #932
=> Updated vocab and vectors with forward method

test/data/test_functional.py, torchtext/csrc/register_bindings.cpp, torchtext/csrc/sentencepiece.cpp, torchtext/csrc/sentencepiece.h, torchtext/data/functional.py
Test against `pytext.utils.file_io.PathManager` and it works with `spm = load_sp_model(PathManager.open('m_user.model', 'rb'))`
=> Update load_sp_model func to accept a file object

test/experimental/test_transforms.py, test/experimental/test_vocab.py, torchtext/csrc/vocab.cpp
`vocab_from_file` func calls `_concat_tokens`, which accidentally sorts the tokens by frequency. However, according to the doc of `vocab_from_file` func ([here](https://github.com/pytorch/text/blob/db31b5dc046345c2ef70a7d578757053e0bd3bd9/torchtext/experimental/vocab.py#L49-L51)),  `vocab_from_file` func read the tokens in a text file and pass them to the constructor of Vocab class as the order appears in the text file.
=> Fix a bug in `torchtext.experimental.vocab.vocab_from_file` function

packaging/pkg_helpers.bash
Default to using the `cpu` directory since the base one is not reliable
=> packaging: Use cpu directory by default

test/data/test_functional.py, torchtext/data/functional.py
This PR:
- adds test for unsupported input type `test_sentencepiece_unsupported_input_type` ([review comment](https://github.com/pytorch/text/pull/965#discussion_r485065199))
- updates error message listing valid input types and type of input given. ([review comment](https://github.com/pytorch/text/pull/965#discussion_r485064957))
Notes:
- Should we raise [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) instead of [RuntimeError](https://docs.python.org/3/library/exceptions.html#RuntimeError)?
- Type annotation and static type checking is another option to do that.
=> add test and update error message for functional.py::load_sp_model

torchtext/experimental/functional.py, torchtext/experimental/transforms.py, torchtext/experimental/vectors.py, torchtext/experimental/vocab.py
Install nightly release on Colab and it fails to load the functions and classes, which are not defined in `__all__` list.
```
import torchtext
from torchtext.experimental import transforms
tokenizer = transforms.basic_english_normalize()
```
Error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-4634c3ce90c6> in <module>()
1 import torchtext
2 from torchtext.experimental import transforms
----> 3 tokenizer = transforms.basic_english_normalize()
AttributeError: module 'torchtext.experimental.transforms' has no attribute 'basic_english_normalize'
```
=> Update __all__ definition in experimental folder

torchtext/experimental/datasets/translation.py
`removed_tokens` is not used, and this PR removes `removed_tokens` token.
=> Remove unused token removed_tokens from translation dataset

test/data/test_builtin_datasets.py, torchtext/experimental/datasets/language_modeling.py, torchtext/experimental/datasets/question_answer.py, torchtext/experimental/datasets/raw/common.py, torchtext/experimental/datasets/raw/language_modeling.py, torchtext/experimental/datasets/raw/question_answer.py, torchtext/experimental/datasets/raw/sequence_tagging.py, torchtext/experimental/datasets/raw/text_classification.py, torchtext/experimental/datasets/raw/translation.py, torchtext/experimental/datasets/sequence_tagging.py, torchtext/experimental/datasets/text_classification.py, torchtext/experimental/datasets/translation.py
Make some updates on the experimental datasets:
- Add `data_select` argument to the raw text classification datasets
- Update the doc strings of the raw text classification datasets.
- Add data_select to raw question answer datasets
- Add data_select support to sequence tagging datasets
=> Consistently support data_select for raw Datasets and update documentation.

test/data/test_builtin_datasets.py, torchtext/experimental/datasets/language_modeling.py, torchtext/experimental/datasets/raw/language_modeling.py
To keep consistent over the datasets, we update the data_select argument in the language modeling datasets and reset the valid entry to the middle.
=> reset valid dataset to the middle of data_select

.circleci/config.yml, .circleci/config.yml.in, packaging/pkg_helpers.bash
Package locations are hard-coded in CCI configuration.
This PR changes them to use `UPLOAD_CHANNEL` so that in `release/*` branch and release tag, they go to release location.
=> Parameterize UPLOAD_CHANNEL

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/run_style_checks.sh, .circleci/unittest/linux/scripts/setup_env.sh
In [Vision-2372](https://github.com/pytorch/vision/issues/2372) we fixed the clang-format version. @mthrok [proposed](https://github.com/pytorch/vision/pull/2872#issuecomment-714495595) to do the same in text.
=> Fixing clang-format version to what PyTorch uses

setup.py, test/data/test_functional.py
Since we added the sentencepiece dependency from the source code, we don't need it in the setup.py file anymore.
=> Remove sentencepiece from setup.py file

torchtext/experimental/datasets/language_modeling.py, torchtext/experimental/datasets/question_answer.py, torchtext/experimental/datasets/sequence_tagging.py, torchtext/experimental/datasets/text_classification.py, torchtext/experimental/datasets/translation.py
Add logging for the experimental datasets:
- text classification
- language modeling
- question answer
- sequence tagging
- translation
The logging information include:
- building vocabulary
- vocabulary length
- building datasets
=> Add logging for experimental datasets

setup.py
Hard locks the package to a specific version of torch if defined
Resolves #1063 
=> setup: Add version for torch dependency

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/setup_env.sh, .circleci/unittest/windows/scripts/environment.yml, .circleci/unittest/windows/scripts/install.sh, .circleci/unittest/windows/scripts/setup_env.sh, packaging/pkg_helpers.bash, test/common/torchtext_test_case.py, torchtext/datasets/translation.py
=> [v0.8.x] Add Python 3.9 support

torchtext/csrc/register_bindings.cpp
This PR adopts `TORCH_LIBRARY_FRAGMENT` to make the TorchScript registration simpler and similar to the PyBind11.
Also the order of registration is changed a bit to match the one in PyBind11.
=> Simplify TorchScript registration with TORCH_LIBRARY_FRAGMENT macro

torchtext/csrc/register_bindings.cpp, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h
Consolidates the pybind11-related things to `register_bindings.cpp` and make `vocab.h` not depend on `pybind11`.
=> Consolidate pybind11 and make vocab.h independent of pybind11

.circleci/config.yml, .circleci/config.yml.in, packaging/torchtext/meta.yaml
Package installation for pytorch binaries was failing out due to
https://github.com/conda/conda-package-handling/issues/71
Default to cpuonly since that won't fail out.
Similar to https://github.com/pytorch/audio/pull/1105
This should resolve issues within the nightly pipeline for conda builds
=> packaging: Specify cpuonly for conda meta.yaml

.circleci/build_docs/commit_docs.sh, .circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py
Copy pytorch/audio#1100 and friends to here, which 
- builds docs on every PR
- pushes the built docs on nightly (to `gh-pages/master`) and when the repo is tagged (to `gh-pages/tag`)
=> build docs and push to gh-pages on nightly

test/data/test_functional.py, test/experimental/test_transforms.py, test/experimental/test_vectors.py, test/experimental/test_vocab.py, torchtext/csrc/regex.cpp, torchtext/csrc/regex.h, torchtext/csrc/regex_tokenizer.cpp, torchtext/csrc/regex_tokenizer.h, torchtext/csrc/register_bindings.cpp, torchtext/csrc/vectors.cpp, torchtext/csrc/vectors.h, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h
This PR makes Regex, RegexTokenizer, Vocab, Vectors and SentencePiece
pickle-able on both PyBind11 and TorchScript.
closes #1085 
1. define `_serialize_XXX` and `_deserialize_XXX` next to these classes
This is the replacement of `_get_states_XXX` and `_set_states_XXX`.
I saw the names of the original functions were flipped, and used wrongly in
`__getstate__` and `__setstate__` so I changed the function names to something
more descriptive and less confusing.
2. Use `c10::intrusive_ptr` as holder for custom class when using pybind11.
This allows to use the same serialization/deserialization function for both
PyBind11 and TorchScript.
See https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#smart-pointers
for the detail of holder.
3. For pickling TorchScript-bound …
=> Make Regex, RegexTokenizer, Vocab, Vectors, SentencePiece pickle-able

.circleci/build_docs/commit_docs.sh
continuation of gh-1105
Remove git pull, which was meant to solve a possible race condition (if between the time the CI run clones the repo, builds the project, builds the docs, and check out the gh-pages branch someone else has pushed a change to the branch), but does not work.
Please trigger a nightly build after merging this to test it out.
=> DOCS: remove 'git pull'

docs/source/datasets.rst
Currently, the `__init__`  documentation does not show up in the documentation for the [Sentiment Analysis datasets](https://pytorch.org/text/stable/datasets.html#sentiment-analysis).  This PR fixes this issue.
=> Fixed Sentiment Analysis Dataset docs

packaging/pkg_helpers.bash
Packages were getting unfairly pinned as needing the `+cpu` version of
pytorch when all versions of pytorch should be ABI compatible when
running cpu-only operations.
This eliminates any suffixed version we may have for torch and makes it
so that torchtext can be installed with any version of torch
Tested with the following script:
```
$ cat <<"EOF" | docker run --rm -i -v $(pwd):/v -w /v python:3.8 bash
#!/usr/bin/env bash
source packaging/pkg_helpers.bash
CU_VERSION=cpu
setup_cuda
setup_pip_pytorch_version
echo "PYTORCH_VERSION=${PYTORCH_VERSION}"
EOF
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.8.0.dev20210113%2Bcpu-cp38-cp38-linux_x86_64.whl (166.7 MB)
Collecting …
```
=> packaging: Always strip +.* for torch dependency

packaging/torchtext/meta.yaml
Fixes nightly conda version by passing through BUILD_VERSION environment variable.
=> Pass BUILD_VERSION env from local shell to conda build.

examples/BERT/README.md, examples/BERT/cross_lingual_mlm_task.py, examples/BERT/model.py
Fairseq published two reference pretrained XLM-R models and we evaluated those two models in the cross-lingual MLM workflow with WikiText2 valid dataset. The perplexity (PPL) is available in the table below: 
Model | Description | #params | vocab size | Download | Perplexity (ppl)
-- | -- | -- | -- | -- | --
xlmr.base | XLM-R using the BERT-base architecture | 250M | 250k | [xlm.base.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/xlmr.base.tar.gz) | 6.85
xlmr.large | XLM-R using the BERT-large architecture | 560M | 250k | [xlm.large.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/xlmr.large.tar.gz) | 5.36
=> Add the option to run a reference MLM workflow with fairseq pretrained XLM-R model

torchtext/data/utils.py
Model name shortcuts no longer work in spacCy 3+ or later
Found while looking into the tutorial build failure in https://app.circleci.com/pipelines/github/pytorch/tutorials/3214/workflows/d79dc18a-734e-4a87-ac73-3a687ae99d56/jobs/58297
=> Replace model with full name when spacy load is used

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/setup_env.sh, .circleci/unittest/windows/scripts/environment.yml, .circleci/unittest/windows/scripts/setup_env.sh, test/data/test_builtin_datasets.py, test/test_build.py, test/translation.py, torchtext/data/field.py, torchtext/data/utils.py
In spacy 3.0 release, the shortcut "en" and "de" have been depreciated. The new language packages in spacy 3.0 introduce BC breaking and this propagates to our datasets. 
However, since the Multi30k dataset is in the nightly release, we don't need to add [BC Breaking] tag.
=> Fix broken CI tests due to spacy 3.0 release

examples/BERT/README.md, examples/BERT/cross_lingual_mlm_task.py, examples/BERT/dist_model.py
I started with looking into the CrossLingualMLMTask model parameters using torchsummary. According to my measurements the Embedding layers has 195841536 params, then we have 12 x 7087872 = 85054464 params of the Encoder layers and 192842128 params on the end layers. 196M + 85M + 193M ~= 474M. Since the largest layers are the first one and the last one, it was quite obvious to split the model right in the middle to form 2 shards with almost equal number of params. XLMRModel holds about 3/5 of params and prevents from dividing the model into two equal parts. Therefore I had to "inline" XLMRModel layers into CrossLingualMLMTask and split its encoder to two sequential encoders. Then I used the pipeline parallelism tutorial and adopted it to DistCrossLingualMLMTask.
The code seems working, but …
=> DistCrossLingualMLMTask with two shards

test/data/test_builtin_datasets.py, torchtext/experimental/datasets/raw/common.py, torchtext/experimental/datasets/raw/language_modeling.py, torchtext/experimental/datasets/raw/question_answer.py, torchtext/experimental/datasets/raw/sequence_tagging.py, torchtext/experimental/datasets/raw/text_classification.py, torchtext/experimental/datasets/raw/translation.py
Add `offset`arg to the raw text datasets.
Remove `setup_iter` func from `RawTextIterableDataset` class
=> Add offset arg in the raw text dataset

examples/BERT/model.py, examples/BERT/ns_task.py, examples/BERT/qa_task.py
Users now can build a custom embedding layer outside the BertModel and pass it there. For example, in XLM-R model, there is no token type embedding layer so users can build a customized embedding layer.
=> Pass an embedding layer to the constructor of the BertModel class

test/data/test_builtin_datasets.py, torchtext/experimental/datasets/language_modeling.py, torchtext/experimental/datasets/question_answer.py, torchtext/experimental/datasets/raw/__init__.py, torchtext/experimental/datasets/raw/common.py, torchtext/experimental/datasets/raw/language_modeling.py, torchtext/experimental/datasets/raw/question_answer.py, torchtext/experimental/datasets/raw/sequence_tagging.py, torchtext/experimental/datasets/raw/text_classification.py, torchtext/experimental/datasets/raw/translation.py, torchtext/experimental/datasets/sequence_tagging.py, torchtext/experimental/datasets/text_classification.py, torchtext/experimental/datasets/translation.py, torchtext/utils.py
Add support for the following behavior
```
train = Multi30k(split='train')
```
currently the user has to do
```
train, = Multi30k(split=('train',))
```
Changes include
Follow-up:
=> Add support for string-typed split values to raw datasets.

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, test/data/test_builtin_datasets.py
Introduces the parameterized module to increase resolution of tests and allow one test per dataset written generically.
Changes include
Follow-up to https://github.com/pytorch/text/pull/1147
=> Add and use parameterized for testing

torchtext/utils.py
Google drive URLs are flaky, because the process sending the request might run into quota limits. This is currently not obvious to the user. In particular they'll see the following confusing error.
```
$ python -c "import torchtext; torchtext.experimental.datasets.raw.AmazonReviewFull()"
Traceback (most recent call last):
[...]
KeyError: 'content-disposition'
```
This PR attempts to detect this situation and throw a more readable exception instead.
```
$ python -c "import torchtext; torchtext.experimental.datasets.raw.AmazonReviewFull()"
Traceback (most recent call last):
[...]
RuntimeError: Google drive link https://drive.google.com/uc?export=download&id=0Bz8a_Dbh9QhbZVhsUnRWRDhETzA is currently unavailable, because the quota was exceeded.
```
Unfortunately it doesn't actually solve the …
=> Detect when Google drive link exceeds quota and throw an error.

torchtext/experimental/datasets/raw/__init__.py, torchtext/experimental/datasets/raw/common.py, torchtext/experimental/datasets/raw/text_classification.py
Currently text classification datasets will download from google drive even if the result already exists on disk, because google drive URLs do not allow to infer the path at which the download result will be stored. This PR addresses this for translation datasets and further introduces torchtext.experimental.datasets.raw.MD5 and NUM_LINES dictionaries to allow for easier access of this meta information. It also fixes meta information for the wrapped dataset factory function to actually contain the defaults for split, root and offset.
=> Add _PATHS to text classification datasets, add global MD5 and NUM_LINES.

torchtext/experimental/datasets/raw/translation.py, torchtext/utils.py
Both WMT14 and IWSLT use Google drive as the data source, but don't check whether the file already exists.
This PR further addresses a bug in download_from_url, where a given relative path would result in an incorrectly inferred root directory without prior path normalization (abspath).
=> Add _PATHS to raw WMT14 and IWSLT

.circleci/config.yml, .circleci/config.yml.in, docs/source/experimental_datasets_raw.rst, docs/source/index.rst, torchtext/experimental/datasets/raw/common.py, torchtext/experimental/datasets/raw/language_modeling.py, torchtext/experimental/datasets/raw/question_answer.py, torchtext/experimental/datasets/raw/sequence_tagging.py, torchtext/experimental/datasets/raw/text_classification.py, torchtext/experimental/datasets/raw/translation.py
This change adds a basic overview of of the raw text datasets in the experimental folder to http://pytorch.org/text/master/.
=> Add raw datasets to website documentation

docs/Makefile, docs/source/conf.py, torchtext/datasets/language_modeling.py, torchtext/datasets/text_classification.py, torchtext/experimental/vectors.py, torchtext/experimental/vocab.py
Similar to what was done in `torchvision` https://github.com/pytorch/vision/pull/3290 and `torchaudio` https://github.com/pytorch/audio/pull/1247
This PR fixes sphinx warnings as well as some other doc layout issues, and sets the 
```py
napoleon_numpy_docstring = False
napoleon_google_docstring = True
```
for sphinx to issue warnings when the wrong parameter syntax is used.
The warnings are now turned into errors. Note: sphinx will now stop compilation at the first warning/error it sees; if we relied on sphinx>=8, we could use the `--keep-going` option to let it finish.
=> Fix sphinx warnings and turn warnings into errors

torchtext/experimental/datasets/raw/ag_news.py, torchtext/experimental/datasets/raw/amazonreviewfull.py, torchtext/experimental/datasets/raw/conll2000chunking.py, torchtext/experimental/datasets/raw/penntreebank.py, torchtext/experimental/datasets/raw/squad1.py, torchtext/experimental/datasets/raw/squad2.py, torchtext/experimental/datasets/raw/udpos.py, torchtext/experimental/datasets/raw/wmtnewscrawl.py, torchtext/utils.py
A few datasets, by default, download all dataset splits even if the user may have only requested a subset. This PR addresses that. It also adds language and year as kwargs to WMTNewsCrawl with corresponding input sanitization. It further standardizes logging in extract_archive across all three compression formats.
=> Avoid unnecessary downloads and extraction for some raw datasets, WMTNewsCrawl input sanitization, more logging

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/environment.yml, .circleci/unittest/windows/scripts/install.sh, packaging/pkg_helpers.bash, test/common/torchtext_test_case.py, torchtext/datasets/iwslt.py, torchtext/datasets/wmt14.py
Cherry picks Python 3.9 support for `master`
=> .circleci: Add Python 3.9 support

torchtext/data/datasets_utils.py, torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/wmt14.py, torchtext/datasets/wmtnewscrawl.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
Every dataset is currently passed a tuple of splits and expected to return a list of datasets. This PR moves this logic into the decorator and frees datasets that choose to use it to only worry about receiving one split and returning one dataset instead.
=> Move loops over splits from datasets into decorator

torchtext/data/datasets_utils.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/sogounews.py, torchtext/datasets/wmtnewscrawl.py, torchtext/utils.py
The creation of some datasets can take up to 20s even if the data has already been downloaded and extracted before. Below is a table of timings on master including scripts that measure it.
```
$ python /tmp/asdf4.py
Dataset,Time(s)
AG_NEWS(split=train),0.04942941665649414
AmazonReviewFull(split=train),10.727782011032104
AmazonReviewPolarity(split=train),11.451766014099121
CoNLL2000Chunking(split=train),0.016519546508789062
DBpedia(split=train),1.1978952884674072
EnWik9(split=train),0.5390405654907227
IMDB(split=train),6.395325183868408
IWSLT(split=train),2.6959946155548096
Multi30k(split=train),0.19001436233520508
PennTreebank(split=train),0.009076595306396484
SQuAD1(split=train),0.049971580505371094
SQuAD2(split=train),0.0696258544921875
SogouNews(split=train),7.2132861614227295 …
```
=> Avoid slow extraction of some datasets by storing additional hashes

docs/source/datasets.rst, test/data/test_builtin_datasets.py, torchtext/data/datasets_utils.py, torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/wmt14.py, torchtext/datasets/wmtnewscrawl.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
This PR extends the docstring header decorator to also optionally take in the number of lines per available split and add them to the documentation. Example doc string:
```
Help on function AG_NEWS in module torchtext.datasets.ag_news:
AG_NEWS(root='.data', split=('train', 'test'))
AG_NEWS dataset
Separately returns the train/test split
Number of lines per split:
train: 120000
test: 7600
Args:
root: Directory where the datasets are saved.
Default: .data
split: split or splits to be returned. Can be a string or tuple of strings.
Default: ('train', 'test')
```
=> Document the number of lines per split

test/data/test_builtin_datasets.py, test/test_build.py, test/test_utils.py, torchtext/data/datasets_utils.py
This PR should trigger the inclusion of Google drive based datasets in the CI cache after the weekly clearing. Also see https://github.com/pytorch/text/pull/1180 . I will merge this once the CI runs clear and come next week we ideally won't see CI failures due to Google drive quota anymore.
=> Reenable all google drive based tests

torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/sogounews.py, torchtext/experimental/datasets/raw/wmt14.py, torchtext/utils.py
Summary:
Following datasets were not taking into account the provided root folder
- AmazonReviewFull
- AmazonReviewPolarity
- SogouNews
Added dedicated WMT14 folder to provided root path as it extract all the files without creating sub-folder
=> resolving download folder for some raw datasets

0.8.1/data.html, 0.8.1/data_functional.html, 0.8.1/data_metrics.html, 0.8.1/data_utils.html, 0.8.1/datasets.html, 0.8.1/examples.html, 0.8.1/genindex.html, 0.8.1/index.html, 0.8.1/nn_modules.html, 0.8.1/py-modindex.html, 0.8.1/search.html, 0.8.1/utils.html, 0.8.1/vocab.html, 0.8/data.html, 0.8/data_functional.html, 0.8/data_metrics.html, 0.8/data_utils.html, 0.8/datasets.html, 0.8/examples.html, 0.8/genindex.html, 0.8/index.html, 0.8/nn_modules.html, 0.8/py-modindex.html, 0.8/search.html, 0.8/utils.html, 0.8/vocab.html
Convert the static version text to links in the 0.8 and 0.8.1 documentation
@brianjo
=> convert version text to link

docs/source/conf.py
The font of text website is bold. Remove the Lato font and the whole `setup` func is not necessary.
=> Remove Lato font

torchtext/data/__init__.py
Changes needed to sync with internal state. This change only includes a change to re-populate ```torchtext.data.Batch``` with ```torchtext.legacy.data.Batch``` for older versions of dependent libraries. This should be removed before the next release.
=> [FBcode->GH] 20210308 Fbsync merge into master: tmp. compatability

examples/BERT/cross_lingual_mlm_task.py
No need to review this PR. No plan to land the change.
This PR registers a PowerSGD communication hook when a DDP model is created.
Please try it on FP32 input data.
=> Enable PowerSGD on XLM-R cross-lingual MLM task

examples/text_classification/train.py
Fixing import issue according to latest changes
=> fixing import issue in text classification example

.circleci/regenerate.py
This PR fixes an issue pointed out by Bandit w.r.t. using autoescape=False with a Jinja2 environment to avoid cross-site scripting vulnerabilities.
Bandit output:
```
>> Issue: [B701:jinja2_autoescape_false] Using jinja2 templates with autoescape=False is dangerous and can lead to XSS. Use autoescape=True or use the select_autoescape function to mitigate XSS vulnerabilities.
Severity: High   Confidence: High
Location: ./.circleci/regenerate.py:184
More Info: https://bandit.readthedocs.io/en/latest/plugins/b701_jinja2_autoescape_false.html
183	    d = os.path.dirname(__file__)
184	    env = jinja2.Environment(
185	        loader=jinja2.FileSystemLoader(d),
186	        lstrip_blocks=True,
187	        autoescape=False,
188	    )
```
=> Fixed jinja2 environment autoescape to enable select extensions

.circleci/utils/test_sort_yaml.py
This PR fixes an issue pointed out by Bandit w.r.t. using `yaml.load`, where it'd allow for unsafe loading of arbitrary objects, by using `yaml.safe_load` instead.
Bandit output:
```
>> Issue: [B506:yaml_load] Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load().
Severity: Medium   Confidence: High
Location: ./.circleci/utils/test_sort_yaml.py:14
More Info: https://bandit.readthedocs.io/en/latest/plugins/b506_yaml_load.html
13	
14	sys.stdout.write(yaml.dump(yaml.load(sys.stdin, Loader=yaml.FullLoader), sort_keys=True))
```
=> Added yaml.safe_load instead of yaml.load

requirements.txt, torchtext/data/datasets_utils.py, torchtext/legacy/datasets/translation.py
This PR fixes an issue pointed out by [Bandit ](https://bandit.readthedocs.io/en/latest/)w.r.t. using the `xml` library to parse untrusted data, by using `defusedxml` instead.
Bandit output:
```
>> Issue: [B314:blacklist] Using xml.etree.ElementTree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.parse with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called
Severity: Medium   Confidence: High
Location: ./torchtext/data/datasets_utils.py:24
More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b313-b320-xml-bad-elementtree
23	    with codecs.open(f_txt, mode='w', encoding='utf-8') as fd_txt:
24	        root = ET.parse(f_xml).getroot()[0]
25	        for doc in …
```
=> Added defusedxml to parse untrusted XML data

.circleci/config.yml, .circleci/config.yml.in
The `build_docs` CI run builds the doc on every PR but the artifacts aren't saved, so we can't access the rendered html files.
This PR saves the artifacts so that the built docs can be browsed on each PR by going in the "Artifacts" tab of the `build_docs` CI run.
=> Store artifacts of rendered docs so that rendered docs can be checked on each PR

docs/requirements.txt, docs/source/conf.py
This PR adds GA support to torchtext. We just rely on the native support from the theme (pytorch/pytorch_sphinx_theme#110)
=> Add Google Analytics support

test/experimental/test_vocab.py, test/experimental/test_with_asset.py, torchtext/experimental/vocab.py
The API for factory functions accept file object when in-fact file name is passed to C++ for building the vocab. This PR removed this discrepancy.
=> Modified experimental vocab factory functions API

test/data/test_builtin_datasets.py, test/legacy/data/test_dataset.py
This PR pulls out remainder of legacy data tests from test_builtin_datasets and put it into dedicated legacy test suite for data.
=> separating legacy tests into dedicated legacy test suite

docs/source/data_functional.rst, torchtext/data/__init__.py, torchtext/data/functional.py
With reference to issue #1296, this is a naive implementation to convert to map-style datasets.
Follow-up:
=> functional to convert iterables into map-style dataset

test/experimental/test_vocab.py, test/experimental/test_with_asset.py, torchtext/csrc/register_bindings.cpp, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h, torchtext/experimental/vocab.py
This PR modifies behavior of Vocab according to the discussions in #1016 and #1027
In Summary we made following changes:
1. Added APIs for setting and getting default index. This index is returns when OOV is queried
2. Added API to reassign token
3. Removed unk token from vocab construction
4. Used TORCH_CHECK Macro for error handling
Please note these changes are BC-breaking and hence we further update the version used for vocab serialization.
Furthermore, we added and modified vocab unit tests to check the added functionality.
=> Added APIs for default index and removed unk token

test/test_vocab.py, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h, torchtext/vocab.py
In #1304, we introduced default index. Although, the API can be used to set the value of default index, it did not allow to unset the  same. This PR modified the API to accept Optional[int]. This will allow user to unset the default token by passing None.
=> modifying default index API to accept None

test/test_vocab.py, torchtext/csrc/register_bindings.cpp, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h, torchtext/vocab.py
We remove the API for reassignment from Vocab as the usage is not so clear and it may confusing functionality to use in practice.
=> removing reassignment API from Vocab

test/test_vocab.py, torchtext/vocab.py
We have ongoing discussions here  #1016 and here #1305 
Although it is not yet clear what is the ideal API for factory functions, we think that providing optional arguments for adding specials at the start or end of Vocabulary can help improve user experience compared to when user is not provided with any options. In this PR we add option to provide special symbols through factory API with the constrain that they can either be added at the end or at the beginning. The order of provided special symbols will be preserved.
=> adding support for special symbols in Vocab factory functions

test/data/test_builtin_datasets.py, torchtext/experimental/datasets/language_modeling.py, torchtext/experimental/datasets/question_answer.py, torchtext/experimental/datasets/sequence_tagging.py, torchtext/experimental/datasets/text_classification.py, torchtext/experimental/datasets/translation.py, torchtext/vocab.py
This PR takes care of small discrepancy w.r.t legacy Vocab in new Vocab factory function where the words are also sorted alphabetically.
It also removed legacy vocab usage from experimental datasets and corresponding unit tests
=> fixing behavior of vocab factory and removing legacy vocab from tests

benchmark/benchmark_vocab.py
Fixing broken benchmark due to removal of experimental datasets (#1329) and renaming experimental vocab to new vocab as we the vocab module is already in beta phase
=> fixing benchmark code

test/legacy/test_vocab.py
Summary:
Fixes https://github.com/pytorch/pytorch/issues/58988.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/59067
Reviewed By: jbschlosser
Differential Revision: D28986642
Pulled By: heitorschueroff
=> up the priority of numpy array comparisons in self.assertEqual (#59067)

torchtext/datasets/imdb.py
Currently, if the path of the working space as a 'pos' in its name, e.g. '/Users/user/Documents/re**pos**itories/<something> since repositories contains 'pos' all samples will be positive and some files that are not samples will be considered as samples .e.g 'labeledBow.feat'
By using this approach this will no longer be an issue.
=> Fix IMDB: all samples are positive

torchtext/csrc/register_pybindings.cpp, torchtext/csrc/sentencepiece.cpp, torchtext/csrc/sentencepiece.h, torchtext/csrc/vectors.cpp, torchtext/csrc/vectors.h, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab.h
Fix some warnings from clang-tidy due to the lack of parameter reference and using emplace_back to improve performance.
=> Some simple c++ refactoring

.circleci/config.yml, .circleci/config.yml.in
Do not assume that default python version conda install is 3.8
=> Fix doc build

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/windows/scripts/environment.yml, docs/requirements.txt, packaging/pkg_helpers.bash, packaging/torchtext/meta.yaml, requirements.txt, torchtext/_download_hooks.py
This PR remove the dependence on iopath introduced in #1319 
This helps resolve issue #1380
=> removing dependence on iopath

torchtext/vocab/vectors.py
Fix examples in `get_vecs_by_tokens` documentation.
=> Fix examples in get_vecs_by_tokens documentation.

README.rst
changing all links from master to main
=> changing README links from master to main

.circleci/config.yml, .circleci/config.yml.in
CCI says circleci/python:3.8 is deprecaetd. Migrating to cimg/python:3.8.
> CircleCI’s latest pre-built container images were designed from the ground up to help your team build more reliably.
> Our new images were built specifically for continuous integration projects and they are our most deterministic, performant, and efficient images yet.
> As of Dec 31, 2021, legacy images will no longer be supported on CircleCI.
Related links
- https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic
- https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
- https://circleci.com/docs/2.0/next-gen-migration-guide
=> Migrate CircleCI docker image

torchtext/models/roberta/__init__.py, torchtext/models/roberta/bundler.py, torchtext/models/roberta/model.py
Follow-up item from #1406 : Extend API to support user-specified configuration and checkpoint
Modifying RobertaModel to directly accept configuration. Users can use this class to create uninitialized model as follows:
```python
from torchtext.models import RobertaEncoderConf, RobertaModel, RobertaClassificationHead
roberta_encoder_conf = RobertaEncoderConf(vocab_size=250002)
encoder = RobertaModel(config=roberta_encoder_conf)
classifier_head = RobertaClassificationHead(num_classes=2, input_dim=768)
classifier = RobertaModel(config=roberta_encoder_conf, head=classifier_head)
```
Users can also use the Bundler API to instantiate model with user-specified checkpoint as follows:
```python
from torchtext.models import RobertaEncoderConf, RobertaModelBundle, RobertaClassificationHead …
```
=> Update RobertaModel to directly take in configuration

test/models/test_models.py, torchtext/models/roberta/modules.py
Add Attention mask to transform encoder modules. The implementation is based on [Encoder layer from fairseq](https://github.com/pytorch/fairseq/blob/0b21875e45f332bedbcc0617dcf9379d3c03855f/fairseq/modules/transformer_layer.py#L20) 
Follow-up:
=> add attention mask to transformer encoder modules

test/models/test_models.py
The non-zero output values are likely affected by platform. To make the test safer, we only like to ensure the output is all zeros for first token.
Follow-up:
=> fix attention mask testing

torchtext/__init__.py, torchtext/models/roberta/bundler.py
This PR fixes the Circle CI model test failures on Windows.
To generate download URLs we used `os.path.join(_TEXT_BUCKET, "xlmr.vocab.pt")`. `os.path.join` is not the right way to join URL paths and must only be used for local OS directory paths. In our case, since `_TEXT_BUCKET` has forward slashes (because it is a URL), `os` library acts smart and on Windows it produces the URL: `https://download.pytorch.org/models/text\xlmr.vocab.pt` which gives a 403 on CURL.
Instead of `os.path.join`, we must use `urllib.parse.urljoin`
=> Fix CircleCI failures on Windows for XLM-R unit tests

test/models/test_models.py
Add Unit tests to test model training:
1. when encoder is not freezed
2. when encoder is freezed
Follow-up:
=> add unit tests for testing model training

test/models/test_models.py, torchtext/models/roberta/bundler.py, torchtext/models/roberta/model.py
This PR changes the Bundle API `from_config` class method name to `build_model` to better reflect the job of this method. Additionally, `strict` option is exposed to the user in order to work with under(over)-specified checkpoint keys.
Other changes (mostly clean-ups):
- Removed the `from_config` class method from the `RobertaEncoder` class. This function doesn't add any value.
- Removed private builder function `_get_model`. This is not really needed since the `build_model` function is doing what's required to build the model.
- Added the `freeze` option to `RobertaEncoder` class. This enables freezing encoder parameters directly inside the class instead of doing it explicitly inside `RobertaModel`.
- Renaming: `override_head` -> `override_checkpoint_head` for `build_model` method
- …
=> change from_config to build_model and other minor clean-ups

test/test_transforms.py, torchtext/transforms.py
Summary: In the construction of Vocab within label transform, the default index is set to 0. This index is returned when OOV token is given. For this transform, the default index should never be set. Otherwise, it will return default index (which is 0) for unknown labels that might get passed (Ideally it should throw error in this case because we do not know what to do when wrong label is passed for query)
Reviewed By: hudeven
Differential Revision: D32610834
fbshipit-source-id: e49385fb313929627c41fc515b6d900a6bfc3591
=> [fbsync] Fix issue in label Transform

test/experimental/test_datasets.py, torchtext/experimental/datasets/sst2.py
Summary:
- Modified SST2 dataset implementation to only return text for test split (since label_ids are not available)
- Updated doc classification datamodule to temporarily use `val_dataset` instead of `test_dataset`
- Updated first line md5 hash for SST2 test split
- Update doc classification module to work with test splits with and without labels
Reviewed By: parmeet
Differential Revision: D32661112
fbshipit-source-id: ef86aea0ce587c5d5282f2caa943b4b0cdf6f54a
=> [fbsync] Fix SST2Dataset test iterator

docs/source/transforms.rst, test/test_functional.py, test/test_transforms.py, torchtext/functional.py, torchtext/models/roberta/transforms.py, torchtext/transforms.py
* This PR updates the annotation types of transforms to `Any`
* Add `Truncate` transform
The transforms and functionals support multiple styles of inputs (both batched and non-batched are supported) as well as sometimes they may support multiple types (refer to Truncate transform added in this PR that can work with both `int` and `str` primitive types). Composability of these transforms and support for torch scriptability may not go hand-in-hand. Below code snippets shows couple of these issues.
```python
import torch
from typing import List, Union
#primitive transform
def foo(input: Union[int, List[int]])->Union[int, List[int]]:
if torch.jit.isinstance(input, List[int]):
return input
elif torch.jit.isinstance(input, int):
return input
else:
raise TypeError
#primitive transform
def …
```
=> Update annotation types of transforms and functionals

.circleci/config.yml, .circleci/regenerate.py, README.rst, setup.py
Python 3.6 reached [EOL](https://endoflife.date/python) last month. PyTorch core is going to do the same in pytorch/pytorch#69005. Other libraries doing the same are:
- Torchvision pytorch/vision#5152
- Torchdata pytorch/data#156
- Torchaudio pytorch/audio#2051
This should also fix the CircleCI failures in 3_6 conda builds
=> Remove Python 3.6 support as it has reached EOL

torchtext/experimental/datasets/sst2.py
TorchData is changing its API, renaming `FileLoader` to `FileOpener`.  See https://github.com/pytorch/pytorch/pull/70367
This PR changes the usage in TorchText experimental to match the new API.
=> Switching to use FileOpener from FileLoader

torchtext/models/roberta/bundler.py
The max sequence length for base architecture is 256. This PR fixes it.
=> fix max sequence length for xlmr transform

torchtext/models/roberta/bundler.py
- Added documentation describing XLM-R, the datasets it was trained on, and relevant license information
=> Updates to XLMR model documentation

test/data/test_builtin_datasets.py, torchtext/data/datasets_utils.py, torchtext/datasets/amazonreviewpolarity.py
Reference Issue: https://github.com/pytorch/text/issues/1494
Summary
* Migrate AmazonReviewPolarity
* Importing torchdata conditional and raising exception during function call if package is not available
* Update CI for datasets testing
=> Migrating AmazonReviewPolarity to datapipes

test/common/parameterized_utils.py
- Both `test/common/assets.py` and `test/common/parameterized_utils.py` files have a constant for the path to the assets directory and a `get_asset_path` method
- We remove these redundant constants/methods from `test/common/parameterized_utils.py` and instead use the implementation from `test/common/assets.py`
- `pytest test/data/test_builtin_datasets.py`
- Note: the above tests only run on circleci and fail when run locally since the datasets are not cached
=> Remove redundant get asset functions from parameterized_utils file

torchtext/datasets/amazonreviewfull.py
=> migrate Amazon Review Full to datapipes.

torchtext/datasets/amazonreviewpolarity.py
This PR fixes the issue with filter logic in split. The current implementation might fail to return proper split if there is a `train` or `test` folder in the dataset path.
=> Fix split filter logic in AmazonReviewPolarity

test/data/test_builtin_datasets.py, torchtext/datasets/ag_news.py
=> migrate AG_NEWS to datapipes.

torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/sogounews.py, torchtext/experimental/datasets/sst2.py
Using an f string populated with a string literal is just that string, but we can just use `os.path.join` instead. 😄
=> use os.path.join for consistency.

README.rst
IterDataPipes do not have `__next__`, so this example no longer works.
=> Remove example using `next(...)` from README

torchtext/datasets/ag_news.py
- The `EndOnDiskCacheHolderIterDataPipe` expects the mode to contain `b` otherwise it tries to read a string. The `HTTPReader` datapipe returns an IOStream of bytes from a given URL.
- By adding `b` to the `mode` param, we can fix the failing CI tests
=> Fixing dataset test failures due to incorrect caching mode in AG_NEWS

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/windows/scripts/environment.yml, packaging/pkg_helpers.bash, packaging/torchtext/meta.yaml
- Replaces pip installs with conda installs where applicable
- Follows torchvision pattern for handling pytorch-mutex which conflicts with cpuonly
=> Attempting to fix version conflict in CI

torchtext/datasets/squad2.py
Migrates dataset in `torchtext/datasets/` per reference impl [here](https://github.com/pytorch/data/blob/main/examples/text/squad2.py). ~Do not merge until #1513 lands~
=> Migrate squad2 to datapipes

test/data/test_dataset_utils.py, torchtext/data/datasets_utils.py, torchtext/datasets/conll2000chunking.py
Migrates dataset in `torchtext/datasets/` 
=> migrate CONLL 2000  to datapipes.

torchtext/datasets/amazonreviewpolarity.py
This PR introduces caching for extracted files. It will help avoid repetitive extractions with every iteration. 
Reference issue: #1526 
command : 
```python
%timeit next(iter(AmazonReviewPolarity(split='train')))
```
Time take without caching: `2.17 s ± 52.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
Time taken with caching: `933 ms ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
Reducing time by almost 50% :)
=> Cache extraction for AmazonReviewPolarity

torchtext/datasets/penntreebank.py
- Migrate PennTreebank
- Importing torchdata conditional and raising exception during function call if package is not available
=> Migrating PennTreebank to datapipes

torchtext/datasets/enwik9.py
- Migrate EnWik9
- Importing torchdata conditional and raising exception during function call if package is not available
=> Migrating EnWik9 to datapipes #1511

test/test_vocab.py, torchtext/vocab/vocab_factory.py
=> add max_tokens kwarg to vocab factory.

torchtext/datasets/wikitext103.py
Migrate WikiText103 to datapipes and add secondary caching
Reference Issue: #1494 and #1526
```
pytest  test/data/test_builtin_datasets.py -v
```
=> Migrate WikiText103 to datapipes

torchtext/datasets/udpos.py
=> migrate UDPOS to datapipes.

torchtext/datasets/multi30k.py
=> migrate Multi30k to datapipes.

test/common/case_utils.py, test/datasets/amazonreviewpolarity_test.py, torchtext/datasets/amazonreviewpolarity.py
Reference Issue: #1493
- Added mocked unit test for AmazonReviewPolarity to test
- Correctness of loaded data using datapipes
- Passing string or tuple to split arguments results in the same iterable dataset
- Creating `TempDirMixin` class to provide easy access to temp dir when testing (similar to the [implementation in torchaudio](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/common_utils/case_utils.py#L17-L44))
- Patching `torchdata.datapipes.iter.util.cacheholder._hash_check` function to return `True`
- Without this, the `OnDiskCacheHolderIterDataPipe` attempts to re-download the dataset since the hash of the full dataset doesn't match the hash of the mocked dataset
` pytest test/datasets/amazonreviewpolarity_test.py`
=> Add AmazonReviewPolarity Mocked Unit Test

test/integration_tests/test_models.py
- Removing unused TEST_MODELS_PARAMETERIZED_ARGS constant from model test (this was missed in #1502)
=> Removing unused TEST_MODELS_PARAMETERIZED_ARGS constant from model test

test/common/case_utils.py, test/datasets/test_sst2.py
Reference Issue: #1493
- Added mocked unit test for SST dataset 
- Added `zip_equal` helper function to help test for unequal dataset lengths ([stackoverflow thread](https://stackoverflow.com/questions/32954486/zip-iterators-asserting-for-equal-length-in-python/32954700#32954700))
- ` pytest test/datasets/test_sst2.py`
=> Add SST2 Mocked Unit Test

test/datasets/test_amazonreviewpolarity.py
- Follow up from #1542
- Patching in `setUp` and `tearDown` methods
- Using `zip_equal` to iterate through datapipes to ensure consistent iterable lengths
=> Updated AmazonReviewPolarity test to be consistent with SST2 test

torchtext/datasets/penntreebank.py
This PR fix the bug in writing downloaded file to disk. It need be dumped as binary ('wb') and not as text/string ('w').
=> [BUG-FIX] fix penn dataset

torchtext/data/datasets_utils.py, torchtext/datasets/iwslt2016.py
Reference #1494 
This is a bit messy, but seems kosher. cc @ejguan for review
=> migrate IWSLT2016 to datapipes.

torchtext/data/datasets_utils.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py
Reference #1494 
We can wait to review this until IWSLT2016 has landed to not duplicate efforts. 😄
=> migrate IWSLT2017 to datapipes.

test/datasets/test_iwslt2016.py
=> mock up IWSLT2016 test for faster testing.

test/datasets/test_multi30k.py
=> Multi30k mocked testing

torchtext/vocab/vocab_factory.py
Fix typo in doc of build_vocab_from_iterator.
=> fix typo in torchtext/vocab/vocab_factory.py

test/datasets/test_amazonreviewfull.py
Reference Issue: #1493
- Added mocked unit test for AmazonReviewFull dataset 
- ` pytest test/datasets/test_amazonreviewfull.py`
=> Add AmazonReviewFull Mocked Unit Test

test/datasets/test_sogounews.py
Reference Issue: https://github.com/pytorch/text/issues/1493
Added mocked unit test for SogouNews dataset
`pytest test/datasets/test_sogounews.py`
=> Add SogouNews Mocked Unit Test

test/datasets/test_cc100.py
=> add CC100 mocking test

torchtext/datasets/conll2000chunking.py
Reference Issue: https://github.com/pytorch/text/issues/1589
- Updated caching datapipe variable names to be consistent with other datasets
- Removed intermediate `conll2000chunking ` folder to download archived files to
=> Updating Conll2000Chunking dataset to be consistent with other datasets

test/datasets/test_conll2000chunking.py
- Fixing test failure caused by #1570 due to saving archive in the wrong folder
`pytest test_conll2000chunking.py`
=> [BUG-FIX] Fixing Conll2000Chunking Test

test/datasets/test_iwslt2017.py, torchtext/datasets/iwslt2017.py
Reference issue: #1493 
This PR do couple of things:
1) Add Mock test similar to #1596. Original credit: @erip due to #1585
2) Fix an issue on IWSLT2017 that created additional texts folder outside of extracted archive
=> Add Mock test for IWSLT2017 dataset

torchtext/data/datasets_utils.py
These functions are all private (and documented as such), so removing them should be fine. Once WMT14 is migrated we can also remove `_read_text_iterator` and `_download_extract_validate`. 
We will also likely want to formally deprecate `_RawTextIterableDataset` which is private, but I have the impression that people will be using it.
=> remove private functions whose responsibilities have been subsumed by datapipes. TODO: migrate WMT14 to remove remaining private dataset utils.

docs/source/datasets.rst, torchtext/datasets/cc100.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/multi30k.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py
- Added dataset docs for SST2 and CC100
- Converted splits to list in dosctring as a followup from https://github.com/pytorch/text/pull/1603#discussion_r804997079
- Reorganized datasets in documentation to be in alphabetical order
=> Added docs for CC100 and SST2

packaging/torchtext/meta.yaml
Experimental features are not available in release branch. Remove it from conda packaging test.
=> remove experimental import in release branch

torchtext/datasets/amazonreviewpolarity.py
- Removing `_add_docstring_header` from `AmazonReviewPolarity` as a followup from https://github.com/pytorch/text/pull/1604#pullrequestreview-880806905
=> Remove _add_docstring_header decorator from AmazonReviewPolarity

torchtext/datasets/amazonreviewpolarity.py
=> [Cherry-pick] Remove _add_docstring_header decorator from amazon review polarity

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/windows/scripts/environment.yml, packaging/pkg_helpers.bash, packaging/torchtext/meta.yaml
This reverts commit a6ae5946e49db2afb2eb8ca5435afaea036077f3.
=> Revert "Attempting to fix version conflict in CI (#1520)"

torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
This may need to wait for appropriate nightlies to be published, but @ejguan suggested this feature will make it into pytorch 1.11 so that's a good sign.
=> prepare datasets for new encoding kwarg.

test/test_transforms.py, torchtext/transforms.py
@ebsmothers reported that current CLIPTokenizer runs into errors when original merges files is loaded from OpenAI. This happens because OpenAI codebase hardcodes the number of merges which torchtext did not do. 
Similarly @ProGamerGov reported #1612 . 
This PR addresses these issues by doing the following:
1. Enable initializing CLIPTokenizer with just the bpe merges file, similar to OpenAI. 
2. Add a `num_merges` param that users can provide.
3. If encoder json is provided, use that to infer number of merges. 
* Added new tests with an example that was failing earlier. 
* Added tests for different types of initialization
```
pytest test/test_transforms.py -k test_clip
```
=> Modify CLIPTokenizer to either infer number of merges from encoder json or take it in constructor

torchtext/csrc/register_pybindings.cpp
Fix for windows builds with python 3.10 , getting rid of ssize_t
This is to fix error when building with Python 3.10 on windows:
Ref: https://app.circleci.com/pipelines/github/pytorch/text/4984/workflows/5df0236c-4758-412d-8a08-e50aa120be39/jobs/166014
Error details:
```
C:\Users\circleci\project\torchtext\csrc\register_pybindings.cpp(123): error C2065: 'ssize_t': undeclared identifier
C:\Users\circleci\project\torchtext\csrc\register_pybindings.cpp(123): error C2146: syntax error: missing ';' before identifier 'length'
C:\Users\circleci\project\torchtext\csrc\register_pybindings.cpp(123): error C2065: 'length': undeclared identifier
C:\Users\circleci\project\torchtext\csrc\register_pybindings.cpp(124): error C2065: 'length': undeclared identifier …
```
=> Fix for windows builds with python 3.10 , getting rid of ssize_t

docs/source/models.rst, test/models/test_models.py, torchtext/models/roberta/__init__.py, torchtext/models/roberta/bundler.py
This PR changes the name of `RobertaModelBundle` -> `RobertaBundle` to keep consistency across domains. Unfortunately, we are already past deadline to cherry-pick this change for 0.12 release. We can incorporate this change in dot release.
=> [BC-breaking] rename Roberta Bundle

test/datasets/test_iwslt2016.py, test/datasets/test_iwslt2017.py
- Followup to #1608 
- Addresses #1607 
- `pytest test_iwslt2016.py`
- `pytest test_iwslt2017.py`
=> Add unicode generation to IWSLT tests (followup to #1608)

examples/tutorials/sst2_classification_non_distributed.py
The installation instructions corresponds to nightly release. As we are getting close to release, we can remove them as users would be able to run this using the released binaries.
=> remove install instructions from tutorial

docs/source/utils.rst, test/data/test_utils.py, torchtext/data/datasets_utils.py, torchtext/utils.py
Summary:
* Removed stale code that is no longer used in the library due to changes in documentation decorators and Datasets migration 
* Removed unicode_csv_reader that is meant for  python 2
=> clean-up stale code

requirements.txt
Installing the requirements breaks starting today due to: https://github.blog/2021-09-01-improving-git-protocol-security-github/
with:
```
pip install --no-cache-dir -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+git://github.com/jekbradbury/revtok.git (from -r requirements.txt (line 11))
Cloning git://github.com/jekbradbury/revtok.git to /tmp/pip-req-build-inn0fxa2
Running command git clone -q git://github.com/jekbradbury/revtok.git /tmp/pip-req-build-inn0fxa2
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
This PR should fix this build issue.
CC @malfet @atalman
=> replace git+git with git+https in requirements.txt

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh
Now that torchdata nightly releases are available, this PR will install that version instead from source. This should reduce the amount of noise coming from accidental torchdata failures.
In addition, some "ci/circleci: unittests" seem to be [failing](https://app.circleci.com/pipelines/github/pytorch/text/5139/workflows/601f2b62-ce43-4f8f-975a-631be15c16f8/jobs/172078) because it cannot find the module `torch` during the installation of `torchdata`. This also fixes that.
=> Install torchdata from nightly release in CI

torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py, torchtext/datasets/sogounews.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
For better consistency among its API names, [TorchData](https://github.com/pytorch/data) deprecated/renamed a few DataPipes' methods in its beta release. This PR update torchtext's usages to align with the latest TorchData API. 
Basically, we are updating `.read_from_ARCHIVE()` to `.load_from_ARCHIVE()`.
There should be no functional changes for torchtext at all. For details about the renaming and deprecation, see the following issue.
* https://github.com/pytorch/data/issues/163
---
The lint failure in CI is pre-existing.
The issue with "ci/circleci: unittests" failing during builds is fixed by this PR:
* https://github.com/pytorch/text/pull/1664.
=> Updating TorchData DataPipe API usages

build_tools/setup_helpers/extension.py, torchtext/csrc/clip_tokenizer.cpp, torchtext/csrc/clip_tokenizer.h, torchtext/csrc/gpt2_bpe_tokenizer.cpp, torchtext/csrc/regex.cpp, torchtext/csrc/regex_tokenizer.cpp, torchtext/csrc/register_pybindings.cpp, torchtext/csrc/register_torchbindings.cpp, torchtext/csrc/sentencepiece.cpp, torchtext/csrc/sentencepiece.h, torchtext/csrc/vectors.cpp, torchtext/csrc/vocab.cpp, torchtext/csrc/vocab_factory.h
**Reference Issue #1644**
- Updated includes to use project root level imports
- This is the first step in breaking up the changes in #1660 and testing the changes within Facebook's internal repo
- Updated include header from `pybind_utils` -> `module_python.h`
- Ensure `python setup.py develop` doesn't cause any build failures 
- Ensure no test failures in OSS CI
- Ensure no failures in internal CI by manually importing this PR and building the repo on FB stack
=> [CMake 1/3] Update C++ includes to use imports relative to root directory

torchtext/transforms.py
This PR fixes the PAD transform test in scripting mode.
The [torch.nn.function.pad](https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html) function expect float value, and when providing with int,  it complains in script mode.
=> fix pad transform test

.circleci/config.yml, .circleci/config.yml.in, .circleci/smoke_test/docker/Dockerfile, .circleci/smoke_test/docker/build_and_push.sh
This PR fixes the smoke tests for torchtext and python 3.9 and 3.10 We will need to rebuild docker image for this.
This is same as [PR audio](https://github.com/pytorch/audio/pull/2348)
=> Fix smoke tests for linux

torchtext/models/roberta/bundler.py, torchtext/models/roberta/modules.py
Summary: Fully remove to_better method by rebuild torchtext TransformerEncoderLayer's load_from_state_dict and init. No more redundant params.
Reviewed By: parmeet
Differential Revision: D36020184
fbshipit-source-id: ccdd6da853a86034762b235cd7d5f793876d16c6
=> [fbsync] Kill to_better by having native load_from_state_dict and init

test/test_transforms.py, torchtext/csrc/clip_tokenizer.cpp, torchtext/csrc/clip_tokenizer.h, torchtext/csrc/gpt2_bpe_tokenizer.cpp, torchtext/csrc/gpt2_bpe_tokenizer.h, torchtext/csrc/register_pybindings.cpp, torchtext/csrc/register_torchbindings.cpp, torchtext/transforms.py
The current GPT2BPE and CLIP Tokenizer transforms returns the encoded token IDs. Based on the user feedback, we learnt that for consistency, it would good to expose the option to return tokens directly instead of their encoded IDs. 
This PR addresses the issue by adding  boolean option `return_tokens` in Tokenizer Transform initialization API that would let users to either return Tokens or their corresponding Token IDs (encoded as strings).
pytest -v -s test/test_transforms.py::TestGPT2BPETokenizer
pytest -v -s test/test_transforms.py::TestCLIPTokenizer
=> Provide option to return splited tokens

test/datasets/test_iwslt2016.py, test/datasets/test_iwslt2017.py
- IWSLT tests fail non-deterministically ([see example failure](https://app.circleci.com/pipelines/github/pytorch/text/5330/workflows/735ab56f-a437-4295-a69a-b5769af309bb/jobs/179403)) in CI which is likely caused by incorrect xml string generation
- We seed the random generator in these tests to make the xml text creation reproducible across runs and prevent these failures
- `pytest test/datasets/test_iwslt2016.py`
- `pytest test/datasets/test_iwslt2017.py`
=> Fix non-deterministic test failures for IWSLT

torchtext/models/roberta/modules.py
Summary:
X-link: https://github.com/facebookresearch/multimodal/pull/34
Pull Request resolved: https://github.com/pytorch/text/pull/1700
Replace the usage of TransformerEncoder by BetterTransformerEncoder
In theory we should be able to remove torchtext.TransformerEncoderLayer after this diff.
Reviewed By: parmeet
Differential Revision: D36084653
fbshipit-source-id: 64ed3810e809fc1db840e75e2e05783089ff31d2
=> [fbsync] Replace TransformerEncoder in torchtext with better transformer

torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py
We will be introducing [a change in `torch`/`torchdata`](https://github.com/pytorch/pytorch/pull/70479) to prevent users from creating multiple iterators from a single DataPipe. In order to not break anything when it lands, this PR update certain DataPipe use cases to avoid creating multiple iterators from a DataPipe. This should not impact any functionality.
Let me know if there are usages of DataPipes outside of `torchtext/datasets`.
=> Updating dataset code to avoid creating multiple iterators from a DataPipe

torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
Replacing lambda functions with regular functions in all datasets because lambda functions are not serializable by `pickle` and serialization is necessary for DataLoader's multiprocessing feature.
If the changes are correct, it should not break any CI.
Fixes part of https://github.com/pytorch/data/issues/397 (TorchData team plans to improve DataLoader as well, see the comments within the issue)
Fixes https://github.com/pytorch/text/issues/1716
=> Replacing lambda functions with regular functions in all datasets

torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
For Datasets, refactor local functions to be global so that they can be pickled
Fixes the issue pointed out here: https://github.com/pytorch/text/pull/1718#discussion_r873266766
=> For Datasets, refactor local functions to be global so that they can be pickled

test/datasets/common.py, torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
=> Add Shuffle and sharding datapipes to datasets

test/datasets/common.py
Addresses comment here https://github.com/pytorch/text/pull/1729#discussion_r876603679
=> Remove redundant dataname in test_shuffle_shard_wrapper

test/datasets/common.py, torchtext/datasets/cola.py, torchtext/datasets/imdb.py, torchtext/datasets/mnli.py, torchtext/datasets/mrpc.py, torchtext/datasets/qqp.py, torchtext/datasets/stsb.py
- Followup to https://github.com/pytorch/text/pull/1718#issuecomment-1128248239
- Adding parameterized test to test pickling for all datasets
-  Refactor local functions to be global so that they can be pickled as a follow up to https://github.com/pytorch/text/pull/1726
`pytest test/datasets/common.py`
=> Adding parameterized dataset pickling tests

test/datasets/test_stsb.py, test/datasets/test_wikitexts.py
This PR fixes issues with STSB and WikiTexts mocked testing. In both the cases mocked files were not written properly in their respective destinations. 
fixes #1735 
cc: @Nayef211 , @VirgileHlav , @VitalyFedyunin
=> Fix STSB and WikiTexts tests

torchtext/__init__.py, torchtext/data/datasets_utils.py
Following conversations in this [post](https://fb.workplace.com/groups/473278361165956/permalink/517067430120382/) internally with @NicolasHug , this is the first step to change the root directory of datasets.
Follow-up:
=> Change root directory for datasets

torchtext/__init__.py
Addresses comment https://github.com/pytorch/text/pull/1740#discussion_r882075619
=> Take TORCH_HOME env variable into account while setting the cache dir

docs/source/_templates/layout.html
1. Fix `collapsedSections is not defined` error.
PyTorch Sphinx theme seems to expect that `collapsedSections`
variable to be defined before its theme.js is executed.
2. Overwrite the link to GitHub project to torchtext
So that documentation link to torchtext's repository instead of
PyTorch core.
=> Fix doc js initialization

.circleci/unittest/windows/scripts/environment.yml, torchtext/__init__.py
The CI jobs [unittest_windows_py3.7](https://app.circleci.com/pipelines/github/pytorch/text/5592/workflows/a789d228-fac5-4b98-9c37-5ee1a2d0d58f/jobs/189407) fails with:
```
error: can't copy 'build\lib.win-amd64-3.7\pyd': doesn't exist or not a regular file
```
Following the changes in https://github.com/pytorch/vision/pull/5868 to fix this
=> Pin setuptools to 58.0.4 on Windows

torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cola.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/mnli.py, torchtext/datasets/mrpc.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/qqp.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/stsb.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
Ticks can result in re-direction to 'https://github.com/pytorch/data%60' instead of 'https://github.com/pytorch/data', which is not a valid resource.
Tested in Colab.
=> Removed ticks (``) from the url under is_module_available

benchmark/benchmark_bert_tokenizer.py, torchtext/__init__.py, torchtext/csrc/bert_tokenizer.cpp, torchtext/csrc/bert_tokenizer.h, torchtext/csrc/register_pybindings.cpp, torchtext/csrc/register_torchbindings.cpp, torchtext/transforms.py
This PR add support for batch tokenizer directly implemented at C++ kernel layer.
It also add benchmarking code for tokenizer. Following result is obtained by running tokenizer on 100000 samples.
```python
python benchmark/benchmark_bert_tokenizer.py --num-samples num_samples
```
**batch size 100**
Running TorchText BERT Tokenizer on non-batched input ... Total running time: 0.0014495829999998655
Running HF BERT Tokenizer (slow) on non-batched input ... Total running time: 0.01610425200000032
Running HF BERT Tokenizer (fast) on non-batched input ... Total running time: 0.0037178359999998634
Running TorchText BERT Tokenizer on batched input ... Total running time: 0.0007109650000001189
Running HF BERT Tokenizer (fast) on batched input ... Total running time: 0.0010531449999997555
**batch …
=> Adding support for batch input in BERT Tokenizer with perf benchmark

CONTRIBUTING.md
- Updating contribution guidelines to add sections for adding third party libraries and custom C++ ops
=> Add contributing guidelines for third party and custom C++ operators

docs/source/datasets.rst, examples/tutorials/sst2_classification_non_distributed.py, torchtext/datasets/ag_news.py, torchtext/datasets/amazonreviewfull.py, torchtext/datasets/amazonreviewpolarity.py, torchtext/datasets/cc100.py, torchtext/datasets/cola.py, torchtext/datasets/conll2000chunking.py, torchtext/datasets/dbpedia.py, torchtext/datasets/enwik9.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2016.py, torchtext/datasets/iwslt2017.py, torchtext/datasets/mnli.py, torchtext/datasets/mrpc.py, torchtext/datasets/multi30k.py, torchtext/datasets/penntreebank.py, torchtext/datasets/qqp.py, torchtext/datasets/sogounews.py, torchtext/datasets/squad1.py, torchtext/datasets/squad2.py, torchtext/datasets/sst2.py, torchtext/datasets/stsb.py, torchtext/datasets/udpos.py, torchtext/datasets/wikitext103.py, torchtext/datasets/wikitext2.py, torchtext/datasets/yahooanswers.py, torchtext/datasets/yelpreviewfull.py, torchtext/datasets/yelpreviewpolarity.py
Closes https://github.com/pytorch/text/issues/1751
Rendered docs: https://output.circle-artifacts.com/output/job/62244176-8485-40e7-8a19-92d89b4a64a3/artifacts/0/docs/datasets.html (not fully up to date)
[Edit: Parmeet]: Rendered docs: https://output.circle-artifacts.com/output/job/a328cfc0-5824-4a1a-a3bf-630e09ff37ee/artifacts/0/docs/datasets.html
@parmeet @Nayef211 the rest of the week is a bank holiday for the UK, so I might not be able to address comments right away. Please feel free to directly edit this PR!
Also FYI @ejguan @NivekT @VitalyFedyunin
=> Add recommendations regarding use of datapipes for multi-processing, shuffling, DDP, etc.

test/datasets/test_qnli.py, test/datasets/test_rte.py, test/datasets/test_wnli.py, torchtext/datasets/rte.py
This PR fixes issues RTE and WNLI testing:
* In both tests, "dataset" directory was not taken into account causing it to download the real data instead of working with mock data
* RTE dataset was not converting string labels into proper integer IDs
* RTE dataset was not parsed properly. Need to pass quoting=csv.QUOTE_NONE in parse_csv to fix the issue.
=> Fix bug in RTE and WNLI testing

test/datasets/test_qnli.py, torchtext/datasets/qnli.py
- QNLI dataset had a bug where we weren't taking into account that the `test` split did not have a label entry
- Additionally the `root_dir` for the mock dataset was not set correctly so the entire dataset was downloaded
- Updated dataset implementation and corresponding test
` pytest test/datasets/test_qnli.py`
=> Fix bug in QNLI dataset and corresponding test

.circleci/config.yml, .circleci/config.yml.in
- Setting release version and base pytorch version as part of the torchtext 0.13 branch cut process
=> Set release version and base pytorch version

torchtext/models/roberta/modules.py
Add src_key_padding_mask arg to fix numerical difference if there is padding.
=> fix missed mask arg in torchtext transformer

test/models/test_transformers.py
Encoder inference should output identical embeddings if given a padded vs. non-padded input (assuming the non-padded data is the same). Check that this is the case. 
We make this check for four paths by setting the below two flags. 
- with_no_grad = [True, False] -> this is performing inference with and without torch.no_grad(). When torch.no_grad() is turned on, we hit the fast path of torch.nn.TransformerEncoder (BetterTransformer). 
- return_all_layers = [True, False]. When set to False, torch.nn.TransformerEncoder is directly called, and when set to True, torchtext encoder loops through torch.nn.TransformerEncoderLayer directly to save the intermediate outputs of each layer.
=> Add test to compare encoder inference on input with and without padding

.github/workflows/build-m1-binaries.yml, packaging/pkg_helpers.bash
This PR adds a tagged build for torchtext, needed to build release
for reference see: https://github.com/pytorch/vision/pull/6140
=> Add m1 tagged build for torchtext

test/data/test_functional.py, torchtext/data/functional.py, torchtext/data/utils.py, torchtext/experimental/transforms.py, torchtext/experimental/vectors.py, torchtext/models/roberta/model.py, torchtext/models/roberta/modules.py, torchtext/nn/modules/multiheadattention.py, torchtext/transforms.py, torchtext/vocab/vectors.py, torchtext/vocab/vocab.py
I added the `-> None` type hint to all the functions in `torchtext/` and `test/` that were missing it, using some [simple regex code](https://stackoverflow.com/questions/64948233/how-to-add-none-to-the-end-of-init-functions-with-notepad).
Adding `-> None` to `__init__` functions is specified by PEP-0484: https://www.python.org/dev/peps/pep-0484/
=> Add missing type hints

.github/workflows/build-m1-binaries.yml
Making sure we build correctly against release branch
=> Making sure we build correctly against release branch (#1790)

benchmark/benchmark_roberta_pipeline.py, benchmark/utils.py, examples/data_pipeline/roberta_dataframe.py, examples/data_pipeline/roberta_datapipe.py
This PR adds benchmark for end-2-end preproc pipeline for RoBERTa based text pre-processing. All the pipelines are based on DataPipes.
* **Pipeline 1 (benchmark_roberta_datapipe):** Using operators/transforms implemented in torchtext and are directly applied on text
* **Pipeline 2 (benchmark_roberta_dataframe):** This pipeline first convert the input text (python tuples) into DataFrame of sizes batch_size on the fly. It then does text processing directly on dataframe.
* **Pipeline 2.2 (Using Ops as UDFs):** This pipeline uses operators implemented in torchtext and are applied to TA dataframe as a UDFs using it's transform API  
* **Pipeline 2.1 (Using Native Ops):** This pipeline used native operators implemented directly in TorchArrow 
Current end-2-end benchmarking results:
Settings: …
=> Add benchmark for roberta prepoc pipelines

torchtext/models/roberta/modules.py
This PR removes the masking at Padded tokens for the input embeddings. 
In fairseq, the masking is applied to input embedding [here](https://github.com/facebookresearch/fairseq/blob/08fe88479f8dd1f53705e203474a031d14cc2d75/fairseq/models/transformer/transformer_encoder.py#L211) but not in HF implementation. This causes MisMatch in output embedding for the padded tokens. 
Ideally, it should not matter the output for padded tokens. Per the investigations from @ebsmothers, it is somehow causing results to differ for MDETR model. In order for Torch MM to upstream dependency on torchtext for RoBERTa encoder, this change is necessary.
=> remove padding mask for input embeddings

benchmark/benchmark_torcharrow_ops.py
This PR add benchmark comparison code for TA ops: Vocab and GPT2BPE tokenizer
Results:
Running times for SST2  train dataset on Macbook pro:
torchtext's GPT2BPE tokenizer: 3.13
torchtext's vocab: 0.32
torcharrow's GPT2BPE tokenizer: 59.13
torcharrow's vocab: 0.03
Interestingly GPT2BPE op is much slower compare to torchtext's implementation whereas vocab op is much faster compared to torchtext's implementation. Need further investigations.
=> Adding Benchmark for TA ops

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, packaging/torchtext/bld.bat, packaging/torchtext/build.sh, setup.py
This commit adds `git` submodule initialization commands at the beginning
of setup, so that third party modules become available automatically.
This makes it possible to install torchtext with a command like
`pip install --no-use-pep517 git+https://github.com/pytorch/text.git`
[example](https://colab.research.google.com/drive/11K2RB540Td0PDniIMjm9bGnXaAH_Z8oY#scrollTo=Vme1nc8DbT7_)
See also:
- https://github.com/pytorch/text/pull/1154
- https://github.com/pytorch/audio/pull/1966
closes #1154
=> Automatically initialize submodule

benchmark/benchmark_torcharrow_ops.py
- Followup to https://github.com/pytorch/text/pull/1807 to fix incorrect inputs to `add_eos` and `add_bos` operator
=> [BUG FIX] Fixing incorrect inputs to add_eos and_bos operators in torcharrow operator benchmark

torchtext/datasets/multi30k.py
- Closes https://github.com/pytorch/text/issues/1756
- Will update the URLs to the original once the server is back up
=> Fix Multi30k dataset urls

.circleci/config.yml, .circleci/config.yml.in
CircleCI is removing Xcode 12.4.0 image on August, and there was a planned
burnout on July 6th. [[detail](https://discuss.circleci.com/t/xcode-image-deprecation/44294?mkt_tok=NDg1LVpNSC02MjYAAAGFbbxbX7nSPCzN0MCKN078pw0VLJ-TMdICr8_gouRNYBM8C55RL8NDKLXA_9CQGPqnhJE5lsSFdetLRF-nH7iBLzoPGBfYpf2vuJ-XkW_C4__4)]
https://app.circleci.com/pipelines/github/pytorch/text/5996/workflows/0bfa021d-b532-4385-b406-c56373c8e9ce/jobs/204435
This commit updates Xcode image to 12.5
=> Update CircleCI Xcode image

torchtext/csrc/CMakeLists.txt, torchtext/csrc/bert_tokenizer.h, torchtext/csrc/clip_tokenizer.h, torchtext/csrc/export.h, torchtext/csrc/gpt2_bpe_tokenizer.h, torchtext/csrc/regex.h, torchtext/csrc/regex_tokenizer.h, torchtext/csrc/sentencepiece.h, torchtext/csrc/vectors.h, torchtext/csrc/vocab.h
TorchText uses dual-binding (PyBind11 and TorchBind) to make custom operations available in Python.
The both binding eventually calls the same implementation contained in `libtorchtext.so`.
The ones bound via PyBind11 (the ones in `torchtext._torchtext`) calls into `libtorchtext.so`.
This means that `libtorchtext.so` has to make the symbols (APIs) used by `torchtext._torchtext` visible.
However, the default visibility of symbols in shared libraries are different in Windows.
On Windows all the symbols are by default hidden. To work around this, we use `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` to expose all the symbols.
There is an upper limit of visible symbols one library fine can contain, and this can be problematic in the future.
(Although it is unlikely that torchtext will hit the limit, …
=> Define TORCHTEXT_API macro for visibility control

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/windows/scripts/environment.yml, requirements.txt
- `sphinx_rtd_theme` is a legacy dependency when torchtext was hosted on Read the Docs ([link](https://torchtext.readthedocs.io/en/latest/))
- Building this dep is causing our unit tests to error out (i.e. [failed CI job](https://app.circleci.com/pipelines/github/pytorch/text/6170/workflows/025cf88a-d431-477f-b921-1663cdc30d20/jobs/211026?invite=true#step-105-601))
=> Remove sphinx_rtd_theme from requirements.txt

.circleci/config.yml, .circleci/config.yml.in, packaging/torchtext/meta.yaml
Recent CircleCI migration https://github.com/pytorch/text/pull/1818
silently bumped the minimum supported macOS version to 11.
PyTorch still supports 10.9 and the ecosystem still uses 10.9.
Issue: https://github.com/pytorch/text/issues/1834
This commit sets MACOSX_DEPLOYMENT_TARGET=10.9, so that binary
distribution are compatible on macOS=10.9.
=> Set MACOSX_DEPLOYMENT_TARGET=10.9 for binary job

torchtext/csrc/bert_tokenizer.cpp, torchtext/csrc/bert_tokenizer.h
=> fix OBO error while reading vocab files with empty lines in BERT tokenizer

.circleci/config.yml, .circleci/config.yml.in, packaging/torchtext/meta.yaml
Recent CircleCI migration https://github.com/pytorch/text/pull/1818
silently bumped the minimum supported macOS version to 11.
PyTorch still supports 10.9 and the ecosystem still uses 10.9.
Issue: https://github.com/pytorch/text/issues/1834
This commit sets MACOSX_DEPLOYMENT_TARGET=10.9, so that binary
distribution are compatible with macOS=10.9.
=> Set MACOSX_DEPLOYMENT_TARGET=10.9 for binary job (#1835)

examples/tutorials/sst2_classification_non_distributed.py
Corrects a typo in the tutorial: 'sentencepiepce' -> 'sentencepiece'
=> Correct typo in SST-2 tutorial

test/common/torchtext_test_case.py, test/csrc/test_gpt2_bpe_tokenizer.py, test/data/test_functional.py, test/data/test_jit.py, test/data/test_metrics.py, test/data/test_modules.py, test/data/test_utils.py, test/datasets/test_enwik9.py, test/datasets/test_qqp.py, test/models/test_models.py, test/prototype/integration_tests/test_models.py, test/prototype/models/test_models.py, test/prototype/models/test_transforms.py, test/prototype/test_functional.py, test/prototype/test_transforms.py, test/prototype/test_vectors.py, test/prototype/test_with_asset.py, test/test_build.py, test/test_functional.py, test/test_transforms.py, test/test_utils.py, test/test_vocab.py
I noticed that some of the tests were missing the  `-> None:` type hint. This PR adds the missing type hint.
=> Added missing `-> None:` type hint to applicable tests

.circleci/config.yml, .circleci/config.yml.in
CircleCI is removing Xcode 12.4.0 image on August, and there was a planned
burnout on July 6th.
https://app.circleci.com/pipelines/github/pytorch/text/5996/workflows/0bfa021d-b532-4385-b406-c56373c8e9ce/jobs/204435
This commit updates Xcode image to 12.5
=> Update CircleCI Xcode image (#1818)

benchmark/benchmark_bert_tokenizer.py
Updated benchmark code to run on pre-defined number of samples and batch size. By running on higher number of samples gives more robust statistics because 1) we show more variable length samples to tokenizer 2) we are running for larger number of batches instead of just 1 as currently the case.
**Number or samples:** 100000
TorchText BERT Tokenizer: 1.7653241670000002
HF BERT Tokenizer (slow): 27.455106365
HF BERT Tokenizer (fast): 5.351107693000003
**Batch-size: 50**
TorchText BERT Tokenizer: 1.376252063
HF BERT Tokenizer (fast): 1.5889374279999995
**Batch-size: 100**
TorchText BERT Tokenizer: 1.3049638119999996
HF BERT Tokenizer (fast): 1.4069846630000002
**Batch-size: 200**
TorchText BERT Tokenizer: 1.275028583
HF BERT Tokenizer (fast): 1.2769447180000002
**Batch-size: 400**
TorchText …
=> Make BERT benchmark code more robust

examples/tutorials/cnndm_summarization.py
Update T5 tutorial to use a beam search for decoding, as opposed to a greedy search.
A beam search was implemented, which keeps track of the log probability of multiple sequences generated for a single input sequence, and prunes them at each iteration to only keep the top `k` most likely. This allows the generator to create sequences that are more probable than those generated by a greedy search. 
We find that the sequences generated via beam search tend to be longer, but still mostly capture the main points expressed in the target summaries. We expect an improvement in the summaries with the addition of constraints such as a length penalty, ngram limit, min length, max length, etc. 
We tested the logic be ascertaining that the sequences generated when `beam_size=1` were the same as those …
=> Updating T5 demo to use beam search for generator

requirements.txt
Torchdata is a requirement to run the test suite, but it doesn't look like this is documented anywhere. This change proposes adding it to the testing section of the requirements.txt.
=> Add torchdata to testing requirements in requirements.txt

test/prototype/integration_tests/test_models.py, torchtext/prototype/models/t5/wrapper.py
Add a wrapper class for the T5 model that takes text as input and outputs the generated text from the decoder
The wrapper class performs the following end-to-end process:
1. transforms input text using `T5Transform` to get truncated and padded token IDs
2. passes resulting model input through t5 model, using a simple beam search generator to produce the output sequence
3. uses transform pipeline to translate the generator output (sequence of token IDs) to text.
Wrapper class accepts either: `configuration` parameter which is a string indicating which bundler object to use (currently only supports `'base'`, but will update once other configurations are added), or parameters `checkpoint`, `t5_conf`, and `transform` if custom model architecture and weights are to be used.
Feed wrapper class …
=> [WIP] wrapper class for end-to-end t5 model

.circleci/config.yml, .circleci/config.yml.in
- CI jobs on MacOS have been failing with the following [error message](https://app.circleci.com/pipelines/github/pytorch/text/6558/workflows/f3d78aac-bd05-4c72-aad9-d469a869b4fb/jobs/225889)
```
failed to create host: Image xcode:12.5 is not supported
```
- According to the [CircleCI website](https://circleci.com/docs/xcode-policy?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQjw3eeXBhD7ARIsAHjssr9nFtoGHLNQhM3Ef0HE9-XQbAmvuCFfEuboIbNneZJl_Syu3IqUyOAaAjTSEALw_wcB), Xcode 12 will be deprecated once Xcode 15 reaches RC which is likely the cause for this failure
- In this PR we bump the Xcode version to be `14.0` in line with [torchvision](https://github.com/pytorch/vision/blob/main/.circleci/config.ym …
=> Update xcode version to 14.0 in CI

examples/tutorials/t5_demo.py, test/datasets/test_cnndm.py, torchtext/datasets/__init__.py, torchtext/datasets/cnndm.py
Currently can only import CNNDM from `torchtext.datasets.cnndm`. Update so that can import from `torchtext.datasetes`
Add CNNDM to `torchtext.datasets.__init__.py` and rename certain class objects to align with expected names in `torchtext.datasets.__init__.py`. Update CNNDM import statements.
`pytest test/datasets/test_cnndm.py` (this imports CNNDM, so import statement is tested)
=> Allow CNNDM to be imported from torchtext.datasets

torchtext/csrc/vocab_factory.h
=> Fix type conversion from py::object to STL container

torchtext/csrc/common.cpp, torchtext/csrc/common.h, torchtext/csrc/vocab_factory.cpp, torchtext/csrc/vocab_factory.h
- https://github.com/pytorch/text/pull/1806 added a `TORCHTEXT_API` to export relevant symbols on Windows platform
- We add the macro to the methods in `common.h` as these are used by functions in `vocab_factory.h`
=> Export symbols in `common.h` file

.circleci/unittest/windows/scripts/environment.yml
Previously, Unit Tests on Windows with Python 3.10 would not complete setup install. After some experimentation, it was discovered that the hangup was caused by having the `spacy` dependency and the `spacy` models both downloaded in by `pip`.  Therefore, the `spacy` dependency was moved to be directly downloaded by `conda`.
Closes #1893
=> Split `spacy` install and `spacy` models downloads

.github/workflows/build-m1-binaries.yml
Usage setup-minicoda action for m1 build
We want to try to address space issues on m1. The following action:
```
pytorch/test-infra/.github/actions/setup-miniconda@main
```
Sets up miniconda in temp folder which should be cleaned between runs
=> Usage setup-minicoda action for m1 build

test/prototype/test_with_asset.py
- The `test_vocab_from_raw_text_file` test is failing on CI for linux platforms due to segmantation faults (see [sample CI job](https://app.circleci.com/pipelines/github/pytorch/text/6713/workflows/016984af-210f-4ec1-ac23-e7b31ea6f465/jobs/231623)).
- Will revert once https://github.com/pytorch/text/issues/1900 is resolved
=> Disable `test_vocab_from_raw_text_file` on Linux

torchtext/models/roberta/modules.py
Summary:
Pull Request resolved: https://github.com/pytorch/text/pull/1896
Turn off mask checking for torchtext which is known to have a legal mask
Reviewed By: zrphercule
Differential Revision: D39445703
fbshipit-source-id: 3f0cacfd39ea11a16c7a06f339872554333b5e97
=> [Cherry Pick]  Turn off mask checking for torchtext which is known to have a legal mask (#1896)

examples/libtorchtext/.gitignore, examples/libtorchtext/tokenizer/CMakeLists.txt
- https://github.com/pytorch/text/pull/1817 missed checking in the `CMakeLists.txt` file within the `examples/libtorchtext/tokenizer` directory
- This led to users such as not being able to build and run the example (https://github.com/pytorch/text/pull/1817#issuecomment-1250224844)
=> Add missing CMakeLists.txt file in `tokenizer` dir

test/torchtext_unittest/prototype/test_functional.py, torchtext/datasets/multi30k.py
- Remove header to skip testing on Windows as https://github.com/pytorch/pytorch/issues/38207 is now closed
- The original Multi30k dataset URL is now back up
Thanks @arnavmehta7 for creating the initial PR for this (#1904). I'm going to land the changes via this PR instead as the other PR wasn't correctly rebased against the `main` branch.
Closes #1904
=> Resolve and remove TODO comments

test/torchtext_unittest/datasets/test_imdb.py, torchtext/datasets/imdb.py
- As per https://github.com/pytorch/text/pull/1911#issuecomment-1253111364, we need to update the label output to be integers instead of strings
- `pytest test/torchtext_unittest/datasets/test_imdb.py`
Closes #1911
=> Resolve inconsistency in IMDB label output

.github/workflows/integration-test.yml, test/integration_tests/prototype/test_models.py, torchtext/prototype/models/t5/bundler.py
* Adds a `build_model_from_huggingface_ckpt` static method to the `T5Bundler`. 
* Adds integration tests to check that an HF model loaded with HF weights and a TorchText T5 model loaded with HF weights both return the same thing when applied to data
Future considerations: This does not support loading from external URLs - planning on adding this in a follow-up Diff from the internal FB side so I can test with Manifold (+ possible GDrive, static public links, Github).
=> [Feature] Add ability to load HF checkpoints into T5 model

test/torchtext_unittest/datasets/common.py
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #1927
We will be deprecating `torch.utils.data.graph.traverse` in the future, replacing it with `traverse_dps`. This PR replaces the usage of that function within one of torchtext's test cases.
=> Updating usage of `torch.utils.data.graph.traverse` in test case

torchtext/csrc/gpt2_bpe_tokenizer.cpp, torchtext/csrc/gpt2_bpe_tokenizer.h, torchtext/csrc/register_pybindings.cpp
Avoid using std::regex and fix lint errors
This change fixes the lint errors raised from merging #1916 into fbcode.
[x ] Fixes
* Removed `std::regex` usage and opted to use `re2`
* Fixed indexing in pre-tokenization step
* Addressed additional linter issue identified internally
* No issue identified in `pre-commit`
* No issue identified with any of the unit tests.
=> Avoid using std::regex and fix lint errors

torchtext/datasets/rte.py
NUM_LINES in torchtext/datasets/rte.py is wrong or maybe out of date (line 24). Update the information in the part
=> update dataset RTE information

test/torchtext_unittest/test_transforms.py, torchtext/csrc/gpt2_bpe_tokenizer.cpp, torchtext/csrc/gpt2_bpe_tokenizer.h
Update decoding logic to handle special tokens
This change is targeted is a follow up to recently added `add_special_tokens` and `decode` features to `GPT2BPETokenizer`. 
The change adds the capability to decode special tokens ids back to text.
[x ] New feature (non-breaking change which adds core functionality)
* Made changes to C++ code (`GPT2BPEEncoder` class) to update the `decode` functionality for special tokens.
* Added unit test to test the new decoding process.
* No issue identified in `pre-commit`
* No issue identified with unit tests.
=> Update decoding logic to handle special tokens

torchtext/prototype/models/t5/modules.py
```
[[​cure_​business]​Torch​Script​Train](https://www.internalfb.com/fblearner/details/379462033/operator/4373394157?tab)Ran for 4 mins 9 s
[Hide logs](https://www.internalfb.com/intern/fblearner/details/379462033?tab=operator_details#)
Try #3
[stderr](https://www.internalfb.com/intern/fblearner/details/379462033?tab=operator_details#)
[stdout](https://www.internalfb.com/intern/fblearner/details/379462033?tab=operator_details#)
[Try #3](https://www.internalfb.com/intern/fblearner/details/379462033?tab=operator_details#)
return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
File "/tmp/jetter.zjtu55hv/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
return optimizer.step(closure=closure, **kwargs)
File …
```
=> Fix device mismatch bug in T5 implementation

packaging/torchtext/meta.yaml, torchtext/transforms.py
Replaces https://github.com/pytorch/text/pull/1952
Fixes https://github.com/pytorch/text/issues/1951
Fixes issues introduced in https://github.com/pytorch/text/pull/1946
Uses the built-in `re` module instead of relying on [`regex`](https://pypi.org/project/regex)
Verified internally using:
```
$ buck2 test @mode/dev pytorch/text/test/torchtext_unittest:test_transforms
```
Signed-off-by: Eli Uriegas <eliuriegas@meta.com>
=> Use re instead of regex

test/torchtext_unittest/datasets/test_cnndm.py, torchtext/datasets/cnndm.py, torchtext/datasets/imdb.py, torchtext/datasets/iwslt2017.py
Cherrypicking https://github.com/pytorch/text/pull/1942
This is the fix https://github.com/pytorch/text/issues/1903
And, the corresponding [PR](https://github.com/pytorch/data/pull/810) from TorchData has been cherry-picked. TorchData's RC binaries have been updated as well.
=> Fixed on_disk_cache issues (#1942) (#1945)

test/smoke_tests/smoke_tests.py
All the other modules are imported when we `import torchtext`, so no need to manually import them all. The recursive import can be seen here: https://github.com/pytorch/text/blob/main/torchtext/__init__.py#L12. There seem to be no lazily imported modules that we need to explicitly check for according to @abhinavarora. So these smoke tests should suffice.
=> [Nova] Updated Smoke Tests that Account for Recursive Import

.github/workflows/build-conda-linux.yml, .github/workflows/build-wheels-linux.yml
Passing an empty string will use the current github ref. So on PR's, it will use the state of the repo as of the PR. For nightly push, it will use the nightly branch. For release, it will use the release branch. Previously, this logic used nightly every time.
=> [Nova] Binary Build Workflows should use PR and not nightly on PRs

.github/workflows/build-wheels-macos.yml
This workflow calls the workflows in pytorch/test-infra to build Mac x86 Wheels for torchtext. This does not change the existing builds/uploads in CircleCI, and should not break any existing jobs/workflows. The purpose of this to help us ensure that these jobs are creating healthy binaries.
TO CLARIFY: this does not upload anything to nightly channels, so this PR has not effect on any existing jobs or distributed binaries.
=> [Nova] Caller workflow for Mac x86 Wheels

torchtext/prototype/models/t5/model.py
In testing on a Bento notebook, located another device mismatch bug that - if user was using a GPU and decoder - the decoder mask would be on the CPU. 
Test plan: N2615118
Should unblock AI for CS workflow and others.
=> Ensure decoder mask is on same device as other tensors

.github/workflows/build-conda-macos.yml
This workflow calls the workflows in pytorch/test-infra to build Mac x86 Conda binaries for torchtext. This does not change the existing builds/uploads in CircleCI, and should not break any existing jobs/workflows. The purpose of this to help us ensure that these jobs are creating healthy binaries.
TO CLARIFY: this does not upload anything to nightly channels, so this PR has not effect on any existing jobs or distributed binaries.
=> [Nova] Add Caller for Mac x86 Conda Binaries

.github/workflows/build-conda-linux.yml, .github/workflows/build-wheels-linux.yml, .github/workflows/build-wheels-macos.yml
If the smoke-test script is not passed to the reusable workflow, it will just use the naive smoke test implemented in the reusable workflow. Passing it (as we do here) will ensure the smoke test script that exists in this repo gets run after the build is complete.
=> [Nova] Pass the smoke test scripts to Reusable Workflow

README.rst
Removing LTS mention and packages from README as it is discontinued.
https://pytorch.org/blog/pytorch-enterprise-support-update/
=> Remove LTS from README

.circleci/config.yml, .circleci/regenerate.py, .github/workflows/build-conda-m1.yml, .github/workflows/build-conda-macos.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/build-wheels-macos.yml
Disabling CircleCI Mac Wheels and Conda binary builds. Need to merge https://github.com/pytorch/text/pull/1990 after to remove the old M1 build workflow.
=> [Nova] Migrate Mac Wheels and Conda Binaries off of CircleCI

.github/workflows/build-conda-linux.yml, .github/workflows/build-wheels-linux.yml
TorchText only has CPU binary builds, but our build matrix was including cuda builds as well. This should remove these unnecessary builds.
=> [Nova] Remove CUDA binary builds

torchtext/datasets/stsb.py
Forward fix caused by deprecating PRs: https://github.com/pytorch/pytorch/pull/89794 and https://github.com/pytorch/data/pull/909
=> Move read_from_tar to load_from_tar

.circleci/config.yml, .circleci/regenerate.py
Linux and Mac Unittests are running via Nova/GHA for some time now. Deprecating the CircleCI ones.
=> [Nova] Remove Linux and Mac Unittests from CircleCI

torchtext/datasets/multi30k.py
**Description**
- This diff changes the expected hash of the test data set back to what it was before https://github.com/pytorch/text/pull/1816 as that hash seems to be expected now. 
- fixes the bug reported here https://github.com/pytorch/text/issues/2001
**Testing**
```
import torchtext
def _main():
train, val, test = torchtext.datasets.Multi30k(language_pair=("de", "en"))
for thing in test:
print(thing)
break
if __name__ == "__main__":
_main()
```
Above script now works
=> update multi30k test dataset hash

torchtext/prototype/models/t5/model.py, torchtext/prototype/models/t5/modules.py
Fixing 🐛 in T5Model when putting both model and input on GPUs.
Trace:
```
Traceback (most recent call last):
File "<string>", line 38, in <module>
File "<string>", line 36, in __run
File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/104a4d5c3a690252/scripts/fni/d2go_scripts/__torchtext_t5_tutorial__/torchtext_t5_tutorial#link-tree/scripts/fni/d2go_scripts/torchtext_t5_tutorial.py", line 25, in <module>
output = model(model_input)["decoder_output"]
File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/104a4d5c3a690252/scripts/fni/d2go …
```
=> Fix device setting for T5 model

.github/scripts/validate_binaries.sh
Fix failures in  https://github.com/pytorch/text/actions/runs/3742919848/jobs/6354468925
The failure was because the script defined "PIP_PREFIX = --pre " then pip install --pre torch torchtext command would install into the PIP_PREFIX directory, in this case '--pre ' directory. 
Solution: rename the PIP_PREFIX to TEXT_PIP_PREFIX to avoid this conflict.
=> Rename variable to avoid conflict with PIP system variable PIP_PREFIX

.github/scripts/validate_binaries.sh, .github/workflows/validate-binaries.yml
Migrated DL validation to test-infra. Added torch pre-install. This simplifies logic needed to be added to Domain Library side.
=> Migrate Validation Workflows to test-infra. Simplify setup logic

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/smoke_test/docker/Dockerfile, .github/workflows/test-linux-cpu.yml, .github/workflows/test-macos-cpu.yml, README.rst, packaging/pkg_helpers.bash, setup.py
According to https://github.com/pytorch/pytorch/issues/80513, PyTorch Core will drop support for 3.7 with the upcoming `torch==2.0.0` release. We should do the same.
Closes https://github.com/pytorch/text/issues/2036
=> Drop support for Python 3.7

test/integration_tests/prototype/test_models.py, torchtext/prototype/models/t5/bundler.py, torchtext/prototype/models/t5/model.py, torchtext/prototype/models/t5/modules.py
Summary:
Pull Request resolved: https://github.com/pytorch/text/pull/2027
[d2go] flan t5 torchtext
This enables support for FLAN-T5 in Torchtext.
So far, we have only enabled FLAN-T5 encoder-only models. If we need to have an encoder-decoder model, it would be straightforward to add support for that.
Reviewed By: joecummings
Differential Revision: D42159825
fbshipit-source-id: 6c2a4430df890131e18d3ebe40bba35ecc6b25b8
=> [CHERRY PICK] flan t5 torchtext (#2027)

.github/workflows/test-linux-gpu.yml
PyTorch core is dropping support for 11.6.
=> Update CUDA version on GPU tests

.github/workflows/codeql.yml
The CodeQL workflow has started failing 3 weeks ago. I traced the issue to a change in how setuptools handles warnings in virtualenvs https://github.com/pypa/setuptools/issues/3772 Reverting to an older setuptools package fixes the issue, but I am not sure how to address properly
=> fix codeql workflow failure

README.rst, requirements.txt
Taking suggestions from @ejguan comments in https://github.com/pytorch/text/issues/2045#issuecomment-1416182472
Closes #2047
=> Added min version requirements and README instructions for torchdata

.github/workflows/test-linux-gpu.yml, pytest.ini, test/torchtext_unittest/prototype/models/gpu_tests/prototype_models_gpu_test.py, test/torchtext_unittest/prototype/models/models_test_impl.py, test/torchtext_unittest/prototype/models/prototype_models_cpu_test.py
=> added prototype GPU tests for T5

.circleci/config.yml, .circleci/regenerate.py
Adding Python 3.11 to the build matrix for Windows wheels (this is still done in circleCI for now).
=> 3.11 Windows Wheels Support in CircleCI

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, .github/workflows/test-linux-cpu.yml, .github/workflows/test-linux-gpu.yml, .github/workflows/test-macos-cpu.yml
We are adding this [patch](https://github.com/pytorch/data/pull/1007) to minimize the hard dependency for TorchData. So, `portalocker` won't be automatically installed when installing with `torchdata`.
This PR would add `portalocker` to ensure CI green
=> Install portalocker for testing

.github/workflows/build-conda-linux.yml, .github/workflows/build-conda-m1.yml, .github/workflows/build-conda-macos.yml, .github/workflows/build-wheels-linux.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/build-wheels-macos.yml
Add triggers for RC branches and tags to all build workflows. This will ensure that the release-candidate builds will run with `CHANNEL=test`.
=> Adding RC triggers for all build jobs

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, packaging/build_conda.sh, packaging/pkg_helpers.bash
Add Windows 3.11 conda.
Same as: https://github.com/pytorch/audio/pull/3071
=> Add windows 3.11 conda

.github/scripts/validate_binaries.sh, test/smoke_tests/smoke_tests.py
* Validate test binaries test
* Fix validate binaries for py3.11
* fix lint
* remove temp change
=> [cherry-pick] [0.15] Fix validation workflow for test channel (#2071)

torchtext/csrc/register_pybindings.cpp
Summary:
- PyBind11 throws an error when decoding a C++ `std::string` which contains incomplete UTF8 byte sequences since the default UTF8 conversion uses `"strict"` error handling ([ref](https://docs.python.org/3/library/codecs.html#error-handlers))
- To resolve user issues (see [post](https://fb.workplace.com/groups/pytorchtext/permalink/899318121386487/)) we set the error handling to `"ignore"` which ignores the malformed data and continues decoding the string
Differential Revision: D43361716
fbshipit-source-id: 4ac488e4b4b894c8049728941a2ee36b1799258a
=> Fix UTF8 decoding error in GPT2BPETokenizer `decode` method

torchtext/csrc/register_pybindings.cpp
Summary:
- PyBind11 throws an error when decoding a C++ `std::string` which contains incomplete UTF8 byte sequences since the default UTF8 conversion uses `"strict"` error handling ([ref](https://docs.python.org/3/library/codecs.html#error-handlers))
- To resolve user issues (see [post](https://fb.workplace.com/groups/pytorchtext/permalink/899318121386487/)) we set the error handling to `"ignore"` which ignores the malformed data and continues decoding the string
Differential Revision: D43361716
fbshipit-source-id: 4ac488e4b4b894c8049728941a2ee36b1799258a
=> [cherry-pick] Fix UTF8 decoding error in GPT2BPETokenizer `decode` method

test/integration_tests/test_generate.py, torchtext/models/t5/model.py, torchtext/prototype/generate.py
Expect batched input to match single input e.g.
1. [seq1, ... seq_m] -> generate -> [output1, ...., output_m]
2. [seq1] -> generate -> [output1]
Before this would not create the same output1. The issue was that the src_key_padding_mask was not being propagated forward. 
Create padding mask and add it to `model_kwargs` and pass it to the forward function.
=> Include padding mask in generation

packaging/install_torchdata.sh
Simplify torchdata version extraction in packaging script
test:
```
conda list -fe torchdata 
torchdata=0.7.0.dev20230328=py310
conda list -fe torchdata | grep torchdata | sed -e 's/torchdata=\(.*\)=py.*/\1/'
0.7.0.dev202303283
```
=> Simplify torchdata version extraction in packaging script

test/torchtext_unittest/models/t5_models_test_impl.py, torchtext/models/t5/model.py
We add a `_shift_right` method to the T5 Model. This is used for training (see [Issue 2127](https://github.com/pytorch/text/issues/2127)).
It shifts an input batch of sequences of token-indices, one index to the right.
Their first token is replaced with the start-of-sequence token, which is the padding-token index for T5 models
=> Add shift-right method to T5 model

torchtext/vocab/vectors.py
Thank you for taking your time. This is my first contribution to this project.
I implemented the method. If I need to change any documentation or anything else, do let me know.
Thanks!
Closes #2140
=> Implementing __contains__ for vocab.Vectors class

test/integration_tests/test_generate.py, torchtext/prototype/generate.py
1. Add the following token-decoding helpers to `GenerationUtils.generate`:
- `top-p`
- `top-k`
- `remove_invalid_values`
- `temperature` (see [Issue 2138](https://github.com/pytorch/text/issues/2138))
2. Add corresponding unit tests and docstrings.
=> Add top-p and top-k sampling to GenerationUtils

test/integration_tests/test_generate.py, torchtext/models/t5/bundler.py, torchtext/models/t5/model.py, torchtext/models/t5/modules.py, torchtext/prototype/generate.py
Makes `GenerationUtils` TorchScript-compatible w/ T5 model.
This PR makes the following changes:
* Makes `GenerationUtils` an `nn.Module` and TorchScript-compatible
* Modifes the output type of T5 (and variants) and has a simpler update function from encoder and decoder
* Adds parameter `with_generation_utils` to `T5Bundle.get_model()` that returns a T5 model wrapped in a TorchScript-compatible `GenerationUtils` class
Testing:
* Passing all old tests for T5 and `GenerationUtils`
* Adds a new test for calling `get_model` with `with_generation_utils=True` and confirming that it is Torchscriptable and provides the correct results.
=> Torchscriptable T5 generation

.github/workflows/test-windows-cpu.yml
Adds Windows CPU Unittests as a GHA Nova Workflow. Supports Python 3.8-3.10 like the current CircleCI job. If these work well for a week or so, we can deprecate the old CircleCI jobs.
=> [NovaX] Windows CPU Unittests

test/torchtext_unittest/test_build.py
- The `test_vocab_from_raw_text_file` test is failing on CI for linux platforms due to the following error `urllib.error.HTTPError: HTTP Error 404: Not Found` (see [sample CI job](https://github.com/pytorch/text/actions/runs/4755755079/jobs/8520868662))
- Will revert once https://github.com/pytorch/text/issues/2160 is resolved
=> Disable `test_download_charngram_vectors` on Linux CI

torchtext/utils.py
Summary:
Followup to D44604474 and D45048667. The previous 2 solutions didn't work because neither `iopath` nor `fcntl` implement platform agnostic locks. Thus the changes in the internal diffs could not be landed on github.
Using [filelock](https://py-filelock.readthedocs.io/en/latest/index.html) should resolve the issue as it implements a platform agnostic file lock mechanism. This solution is also used by PyTorch Core to implement locking (see [code pointer](https://github.com/pytorch/pytorch/blob/bb830224e3e98732c8f26c1f179ff770f07fd543/torch/_inductor/codecache.py#L263-L268)).
Reviewed By: debowin
Differential Revision: D45234254
fbshipit-source-id: 2285f94b13e36685ec6a5c1c4d2cd74dee9e0431
=> Use `filelock` library for file downloads

.flake8, .pre-commit-config.yaml, test/torchtext_unittest/data/test_jit.py
Add TorchFix linter and fix deprecated usages of `assert_allclose` to make it pass.
Also move the comments in the flake8 config to separate lines, as more modern flake8 versions do not support inline comments for any of the keys - https://flake8.pycqa.org/en/latest/user/configuration.html
The bandit failure and M1 failures are pre-existing.
=> Add TorchFix linter

torchtext/datasets/multi30k.py
- Update links to multi30k dataset to user hosted one since original servers are down
See https://github.com/pytorch/text/issues/1756 for tracking
=> Update links to multi30k dataset since original servers are down

.github/workflows/build-conda-linux.yml, .github/workflows/build-conda-m1.yml, .github/workflows/build-conda-macos.yml, .github/workflows/build-conda-windows.yml, .github/workflows/build-docs.yml, .github/workflows/build-wheels-linux.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/build-wheels-macos.yml, .github/workflows/build-wheels-windows.yml, .github/workflows/integration-test.yml, .github/workflows/lint.yml, .github/workflows/test-linux-cpu.yml, .github/workflows/test-linux-gpu.yml, .github/workflows/test-macos-cpu.yml, .github/workflows/test-windows-cpu.yml, .github/workflows/validate-binaries.yml, packaging/install_torchdata.sh
TorchText release only changes
=> [Release 0.16] Release only changes

notebooks/torchscriptable_t5_with_torchtext.ipynb
This notebook is an example of a (working) "Hacky" solution for wrapping the full 'generate' functionality inside a "forward" function. The perpose of this is to start a discussion and be a suggention on how to make the this functionality TorchScriptable.
To do so I:
1. Inherited from T5Model:
- extracted the decoding code from t5.forward() function to a standalone 'decode' function that returns a specific type.
- added the GenerationUtils's 'generate' functionality as a class method (similar to HuggingFace).
2. Added TorchScriptableT5, a module that implements the full generative logic in the forward method.
3. Helper classes that build a jit (TorchScript) model from a predefined T5 Bundle
=> Added notebook torchscriptable_t5_with_torchtext.ipynb

.github/workflows/build-conda-m1.yml, .github/workflows/build-wheels-m1.yml
There is a new label for our macOS runners: "macos-m1-stable". All runners labeled "macos-m1-12" should be switched to "macos-m1-stable". [Here](https://fb.workplace.com/groups/pytorch.dev.perf.infra.teams/permalink/7546708885348237/) you can find more detailed info.
=> Migrate the macOS runners label from macos-m1-12 to macos-m1-stable

torchtext/datasets/iwslt2017.py
Fix #2189 
This is a fix for broken link for IWSLT2017 dataset
Unfortunately, IWSLT2016 data is now disappeared (https://drive.google.com/file/d/1l5y6Giag9aRPwGtuZHswh3w5v3qEz8D8/view?usp=sharing)
So I could not fix that.
=> fix IWSLT2017_link

.github/workflows/validate-binaries.yml
Adds option to validate against a specific version of pytorch
=> Add version to validate from torchtext validate binaries call

torchtext/__init__.py, torchtext/data/__init__.py, torchtext/datasets/__init__.py, torchtext/experimental/__init__.py, torchtext/functional.py, torchtext/models/__init__.py, torchtext/nn/__init__.py, torchtext/prototype/__init__.py, torchtext/transforms.py, torchtext/utils.py, torchtext/vocab/__init__.py
Test plan:
Every single one of these calls will raise the warning:
<details>
```bash
python -c "from torchtext import datasets"
python -c "import torchtext.datasets"
python -c "from torchtext.datasets import AG_NEWS"
python -c "from torchtext import data"
python -c "import torchtext.data"
python -c "from torchtext.data import custom_replace"
python -c "from torchtext import models"
python -c "import torchtext.models"
python -c "from torchtext.models import ROBERTA_BASE_ENCODER"
python -c "from torchtext import nn"
python -c "import torchtext.nn"
python -c "from torchtext.nn import InProjContainer"
python -c "from torchtext import utils"
python -c "import torchtext.utils"
python -c "from torchtext.utils import LOCK_TIMEOUT"
python -c "from torchtext import vocab"
python -c "import …
```
=> Add removeable warnings indicating this is the last release

setup.py, torchtext/__init__.py, torchtext/data/__init__.py, torchtext/datasets/__init__.py, torchtext/datasets/cnndm.py, torchtext/experimental/__init__.py, torchtext/functional.py, torchtext/models/__init__.py, torchtext/nn/__init__.py, torchtext/prototype/__init__.py, torchtext/transforms.py, torchtext/utils.py, torchtext/vocab/__init__.py
Co-authored-by: Nicolas Hug <contact@nicolas-hug.com>
Fix torchdata import error (#2242)
=> [Release 0.18] Add removeable warnings indicating this is the last release (#2248)
